Making email optional for gift
Plant-for-the-Planet-org/planet-webapp pull request #1049
Opened 2021-05-07 13:05 UTC by harshvitra

2021-06-15 07:49 UTC, norbertschuler requested changes

2021-06-15 07:49 UTC, norbertschuler commented on src/features/donations/components/treeDonation/GiftForm.tsx
> +import { InputAdornment } from '@material-ui/core';
I wonder where this is used?

2021-06-15 07:49 UTC, norbertschuler commented on src/features/donations/components/treeDonation/GiftForm.tsx
> +                name={'giftMessage'}
The input given for the gift message always gets lost when navigating back for this form if the gift email was entered and also if no gift email was specified:

<img width="408" alt="Bildschirmfoto 2021-06-15 um 09 42 28" src="https://user-images.githubusercontent.com/1532418/122013897-ebe3fe80-cdbe-11eb-8e5c-e91c474bb931.png">

2021-06-15 07:53 UTC, norbertschuler commented
- [ ] Not giving an email for a gift donation results into this view in the backend (develop):

<img width="1259" alt="Bildschirmfoto 2021-06-15 um 09 51 50" src="https://user-images.githubusercontent.com/1532418/122014361-601ea200-cdbf-11eb-9289-f8512bffe3d1.png">

2021-07-20 12:01 UTC, norbertschuler commented
> * [ ]  Not giving an email for a gift donation results into this view in the backend (develop) for the gift list and also in the donation details view, e.g.:

This is working now:

<img width="1132" alt="Bildschirmfoto 2021-07-20 um 14 00 07" src="https://user-images.githubusercontent.com/1532418/126320267-53c40baf-349a-46b6-aaca-740dedf4992c.png">
<img width="1355" alt="Bildschirmfoto 2021-07-20 um 14 00 39" src="https://user-images.githubusercontent.com/1532418/126320273-6e0e4d46-b934-4af1-8ffa-0fcb8ca0e556.png">

2021-08-08 08:25 UTC, norbertschuler commented on src/features/donations/components/treeDonation/GiftForm.tsx
> +                name={'giftMessage'}
@harshvitra maybe if you have time you can work on this to get this pull request finished?

2022-01-06 11:00 UTC, sarveshpro commented
Donations will be replaced by `planet-donations`

2022-01-06 11:00 UTC, closed without merging