Trigger donation popup
Plant-for-the-Planet-org/planet-webapp pull request #1082
Opened 2021-05-28 09:09 UTC by rishsingh07

Trigger donation popup

2021-05-28 09:17 UTC, sagararyal commented
Remove the console.log 
Besides that it looks good.

2021-05-28 09:23 UTC, norbertschuler requested changes
Tested https://planet-webapp-3qjq4hcx9-planetapp.vercel.app/community-based-restoration-at-el-silencio-natural-reserve#donate showing a popup and https://planet-webapp-3qjq4hcx9-planetapp.vercel.app/community-based-restoration-at-el-silencio-natural-reserve is not showing anything. Seems to work, but there is a error like
```
TypeError: Cannot read property 'includes' of undefined
    at _.fz.h (m=IZT63,ws9Tlc,p8L0ob,vfuNJf,PrPYRd,NpD4ec,Y2UGcc,SF3gsd,Ru0Pgb,hc6Ubd,ZyYHPb,Das5Le:441)
    at hz (m=IZT63,ws9Tlc,p8L0ob,vfuNJf,PrPYRd,NpD4ec,Y2UGcc,SF3gsd,Ru0Pgb,hc6Ubd,ZyYHPb,Das5Le:144)
    at _.jz.next (m=IZT63,ws9Tlc,p8L0ob,vfuNJf,PrPYRd,NpD4ec,Y2UGcc,SF3gsd,Ru0Pgb,hc6Ubd,ZyYHPb,Das5Le:145)
    at m=IZT63,ws9Tlc,p8L0ob,vfuNJf,PrPYRd,NpD4ec,Y2UGcc,SF3gsd,Ru0Pgb,hc6Ubd,ZyYHPb,Das5Le:145
    at new Promise (<anonymous>)
    at kz (m=IZT63,ws9Tlc,p8L0ob,vfuNJf,PrPYRd,NpD4ec,Y2UGcc,SF3gsd,Ru0Pgb,hc6Ubd,ZyYHPb,Das5Le:145)
    at Object._.lz (m=IZT63,ws9Tlc,p8L0ob,vfuNJf,PrPYRd,NpD4ec,Y2UGcc,SF3gsd,Ru0Pgb,hc6Ubd,ZyYHPb,Das5Le:146)
    at KU (m=IZT63,ws9Tlc,p8L0ob,vfuNJf,PrPYRd,NpD4ec,Y2UGcc,SF3gsd,Ru0Pgb,hc6Ubd,ZyYHPb,Das5Le:440)
    at _.fz.h (m=IZT63,ws9Tlc,p8L0ob,vfuNJf,PrPYRd,NpD4ec,Y2UGcc,SF3gsd,Ru0Pgb,hc6Ubd,ZyYHPb,Das5Le:440)
    at hz (m=IZT63,ws9Tlc,p8L0ob,vfuNJf,PrPYRd,NpD4ec,Y2UGcc,SF3gsd,Ru0Pgb,hc6Ubd,ZyYHPb,Das5Le:144)
```

Unfortunately with webpack5 source map generation on Vercel seems to have a problem, so we do not get a clear stacktrace.

2021-05-28 09:23 UTC, norbertschuler commented on pages/[p].tsx
> +console.log(router.asPath,"router")
please remove before merging

2021-05-28 09:28 UTC, rishsingh07 commented on pages/[p].tsx
> +console.log(router.asPath,"router")
already removed

2021-06-01 10:26 UTC, harshvitra approved these changes

2021-06-04 15:09 UTC, merged