Added classification of project
Plant-for-the-Planet-org/planet-webapp pull request #1238
Opened 2021-09-08 07:11 UTC by rishsingh07

Removed comments to show classification of the project.

2021-09-08 09:18 UTC, norbertschuler commented
- [ ]  Did we also want to be able to filter the project list for a classification? (Or maybe as a technical solution just add the ability to use the - translated - classification string as a search term?)

2021-09-08 09:24 UTC, sarveshpro commented
Can you increase the minimized height of the container so that the back button does not overlap on the classification text
https://user-images.githubusercontent.com/27153515/132483170-62b1df91-90d8-4dcb-b043-092b8c9d85da.mp4

2021-09-08 09:33 UTC, sarveshpro requested changes

2021-09-08 09:33 UTC, sarveshpro commented on src/features/projects/components/projectDetails/getProjectClassification.ts
This needs to be translated. you don't really need a switch case just make `t(project.classification)` and add all possible values to translation file. you might want to check if `project.classification` exists first.

2021-09-09 14:44 UTC, sagararyal commented on public/static/locales/en/donate.json
> +  "other-planting": "Other Planting"
@rishsingh07 I suggest following one standard here.

2021-09-09 15:46 UTC, sagararyal commented
can you add
case "mangroves"  = Mangroves

2021-09-14 00:18 UTC, merged