Mega Menu
Plant-for-the-Planet-org/planet-webapp pull request #1320
Opened 2021-11-10 10:32 UTC by rishsingh07

To do: 

- [ ] Transition when menu appears.
- [ ] Translation to be added.

2021-11-10 11:52 UTC, norbertschuler requested changes

2021-11-10 11:52 UTC, norbertschuler commented on public/tenants/planet/config.ts
> +            title: 'Overview',
This solution does not consider translating resources. Please use the `title` as a key for a translation resource, e.g. `overview` -> `Overview` as at https://github.com/Plant-for-the-Planet-org/planet-webapp/blob/ef8e93859407c7d9a2cf91a26c6120e3b1c001da/src/features/common/Layout/Navbar/index.tsx#L162

2021-11-12 13:59 UTC, norbertschuler requested changes
You should talk to @sarveshpro and find a decent common solution :-)

2021-11-12 13:59 UTC, norbertschuler commented on src/features/common/Layout/Navbar/index.tsx
> +                        ''}
This leads for wrong links (just https://planet-webapp-8c27paq4u-planetapp.vercel.app/) for French, Italian and Portuguese. There should be a default link without a locale if no i18n.language matches (as maybe we add further languages in the future).

2021-11-16 10:13 UTC, tejassonar commented
![image](https://user-images.githubusercontent.com/65854629/141966205-d2c075a8-b001-45d9-94af-0a498babbc5c.png)

On small device, icons are overlapping

2021-11-16 10:41 UTC, rishsingh07 commented
> ![image](https://user-images.githubusercontent.com/65854629/141966205-d2c075a8-b001-45d9-94af-0a498babbc5c.png)
> 
> On small device, icons are overlapping

It's happening because of language. Can be solved in a different PR I guess.

2021-11-17 07:17 UTC, norbertschuler requested changes

2021-11-17 07:17 UTC, norbertschuler commented on src/features/common/Layout/Navbar/index.tsx
> +  const lang_path = {
Please use https://github.com/Plant-for-the-Planet-org/planet-webapp/blob/develop/src/utils/constants/wpLanguages.ts which @sarveshpro added for his implementation of language dependent Wordpress links (we need to have a common software architecture and do not build stuff twice).

2021-11-17 07:35 UTC, norbertschuler commented
- [ ] The Mega menu is not dark mode compatible yet:

<img width="376" alt="Bildschirmfoto 2021-11-17 um 08 35 00" src="https://user-images.githubusercontent.com/1532418/142156101-44ca11ba-bffa-4188-b2f7-f3f1a7758e94.png">

2021-11-19 07:36 UTC, norbertschuler approved these changes
LGFM (tests are failing, but I think not because of this pull request)

2021-11-19 10:42 UTC, sarveshpro requested changes
Translation seems to be broken for some elements
![image](https://user-images.githubusercontent.com/27153515/142609639-8201cde0-71df-43a8-85b9-405c09874321.png)

2021-11-19 11:30 UTC, sarveshpro commented
About us button doesn't have `cursor: pointer`, please add it to show that the button is clickable.
![image](https://user-images.githubusercontent.com/27153515/142615253-f61413a4-bdfb-4cb0-ba1e-22c845542479.png)

2021-11-21 16:01 UTC, sarveshpro approved these changes

2021-11-22 15:41 UTC, merged