Explore Layers
Plant-for-the-Planet-org/planet-webapp pull request #138
Opened 2020-09-03 04:44 UTC by sarveshpro

Changes in this pull request:
- Explore Toggles

2020-09-03 04:45 UTC, sarveshpro commented
Does anyone have an insight on how to use ESRI tiles in Mapbox?
https://storymaps.esri.com/stories/2019/anthropocene-atlas/3-forests.html
https://tiles.arcgis.com/tiles/nzS0F0zdNLvs7nc8/arcgis/rest/services/Tree_Cover_2000_Bright_Green/MapServer/4?f=pjson

2020-10-29 13:13 UTC, norbertschuler commented on src/features/public/Donations/components/MapboxMap.tsx
> +              ' https://earthengine.googleapis.com/map/80c988d5e8f6021ef9e6d2447f405c79/{z}/{x}/{y}?token=a5a5893006a0ea587845708b078df9ca',
Trying this locally is giving me errors right now:
```
Request URL: https://earthengine.googleapis.com/map/80c988d5e8f6021ef9e6d2447f405c79/3/1/1?token=a5a5893006a0ea587845708b078df9ca
Request Method: GET
Status Code: 404 
```

2020-10-29 13:16 UTC, norbertschuler requested changes

2020-10-29 13:16 UTC, norbertschuler commented on src/features/public/Donations/components/MapboxMap.tsx
> +                {isMobile ? null : 'Explore'}
Please add `Explore` as a new translation resource with i18n here!

2020-10-29 13:16 UTC, norbertschuler commented on src/features/public/Donations/components/MapboxMap.tsx
> +                      label="Forest"
Please also use translation resources for all of the labels.

2020-11-04 07:39 UTC, closed without merging