Remove donations code
Plant-for-the-Planet-org/planet-webapp pull request #1428
Opened 2022-03-04 06:56 UTC by sarveshpro

### To test -
- Do we need Legacy Donations - `donation-payment/[code]` it gets removed in this PR
- Share Functionality was moved out of the donations folder
- `/payment-status` -  functionality restored
- `/claim/[code]` - functionality restored

2022-03-04 07:01 UTC, sagararyal commented
#### 📝 Changed routes:


| [**/claim/\[type\]/\[code\]**](https://planet-webapp-mvs3l7f4v-planetapp.vercel.app/claim/[type]/[code]) | [**/donation-payment/\[code\]**](https://planet-webapp-mvs3l7f4v-planetapp.vercel.app/donation-payment/[code]) |
|:-:|:-:|
|<a href="https://planet-webapp-mvs3l7f4v-planetapp.vercel.app/claim/[type]/[code]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/wvge5cuhdJyBh4Wy6Cm_3hai6Y1gMbNPyCigaIDyr2SIxU8LZHkHfO9AH8_T-4rWDZqWP_g2zMKnw6Qcx05TRg.png&w=600" alt="Screenshot of /claim/[type]/[code]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/sI10yDDFPvufdLl3VrvZ_TyRO2m0GXM2sYBQpb2_zhnibsCrShh8QNi7tRdPBCkL9PHdYmJokWowlGiSzCrcFw.png">(view full size)</a> |<a href="https://planet-webapp-mvs3l7f4v-planetapp.vercel.app/donation-payment/[code]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/HEYLUQWTlk51pZYg4WwoJFe0GMguf_HNpKJ8m4ly6hdN18zUI1V7BzMPmR60eeam7BmfEMHc_GOjZrWqZ9ai6Q.png&w=600" alt="Screenshot of /donation-payment/[code]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Zu3XOp1oQn5KK4SxduhGSDnmsdeY3bxdGdmnsNdjEVXa8iWZ0BcyR2FEQt39BuYvBinZqp5V7JYk9L1wOVCw3A.png">(view full size)</a> |



| [**/**](https://planet-webapp-mvs3l7f4v-planetapp.vercel.app/) | [**/payment-status**](https://planet-webapp-mvs3l7f4v-planetapp.vercel.app/payment-status) |
|:-:|:-:|
|<a href="https://planet-webapp-mvs3l7f4v-planetapp.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/282_CVYaRQi6nxCNuISTbyRFTFjdAz8sQY_nEAZxxgAk9tO2uioyB1sD0Z1fHHpJq9m7VlIHAQ9gdoTx9P-KpA.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/kBJlgzpTmYtB7gVUDBNehGMUBfBCADJbgr0OhHDjlF8FKcIwpg-JyocvYsPl6oQnZROD3KLsCZjm2ab21pnU6g.png">(view full size)</a> |<a href="https://planet-webapp-mvs3l7f4v-planetapp.vercel.app/payment-status"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/9SN2gThdYSFZJ9ciGqIr8nohseMP-9dvt-RU7zbZTEgJI1IEoWqglimPrDt2V90U0yjLR093yf1vJ7hGAbn4CQ.png&w=600" alt="Screenshot of /payment-status" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/CjPfTPqr22aDrT4uPB2-xxZzGhvt2v9CfIf29HwQjLBxOHy9CMsmzz4wLavcDV9NCN5PsYJQVo-f7LcfECcGTg.png">(view full size)</a> |







Commit 613dd2e976e071bc541c75f738de395fad6f48f1 (https://planet-webapp-mvs3l7f4v-planetapp.vercel.app).

2022-03-06 12:54 UTC, sagararyal submitted a review, later dismissed
remove all legacy donations code and remove packages.

2022-03-08 04:41 UTC, sarveshpro commented
> remove all legacy donations code and remove packages.

Done

2022-03-08 05:54 UTC, ankitecd requested changes
> Did `npx depcheck` and found the below unused packages.
> Can you check and resolve the same?
> 

Deleted most of them, unfortunately, some of them I had to restore because they are needed `depcheck` couldn’t determine their dependency.

2022-03-09 14:23 UTC, sagararyal commented
@sarveshpro can we also remove unused translation resources.

2022-03-13 09:08 UTC, norbertschuler commented
> @sarveshpro can we also remove unused translation resources.

Due to the nature of JavaScript I think there is no tool to check for unused resources (also some resource name are defined dynamically). So we would need to check them manually which probably is quite a time consuming task to do.

2022-03-13 09:30 UTC, norbertschuler approved these changes
I tested redeeming a code and it still works. Also the other parts of the website I click through still seem to work, but I am probably do not covered 100% with my manual tests.

2022-03-13 09:30 UTC, norbertschuler commented on pages/payment-status.tsx
>  import { useRouter } from 'next/router'
I am not sure if this page is still used?

2022-03-13 09:35 UTC, norbertschuler commented
> * Do we need Legacy Donations - `donation-payment/[code]` it gets removed in this PR

This was for older versions of the Treecounter-App, but hopefully nobody is using these old versions any more. I think we do not have to support them any more.

2022-03-22 07:07 UTC, ankitecd approved these changes
Looks good

2022-03-22 07:18 UTC, merged