Fix/navlink active
Plant-for-the-Planet-org/planet-webapp pull request #1442
Opened 2022-03-11 14:35 UTC by sunilsabatp

Fixes #

Changes in this pull request:
-Fix all nav link being active on sub link item being selected

2022-03-11 15:04 UTC, sagararyal commented
- [ ] Translation is broken on this PR

<img width="317" alt="Screen Shot 2022-03-11 at 4 03 43 PM" src="https://user-images.githubusercontent.com/5401575/157893037-c4345fbd-df82-41f3-926a-f6b031569a9d.png">

2022-03-12 14:00 UTC, norbertschuler commented
- [ ] Is it possible to keep the menu item expanded where the subitem got selected? Currently for me it get's closed after selecting the sub menu item:

<img width="1173" alt="Bildschirmfoto 2022-03-12 um 14 57 49" src="https://user-images.githubusercontent.com/1532418/158020894-1f5ecc31-3fef-4efa-97ce-37995a885e21.png">

2022-03-12 14:32 UTC, norbertschuler commented
> * [ ]  Translation is broken on this PR

They is a comma missing in the `me.json` file with the English translations. Rebasing this PR onto develop would fix this.

2022-03-12 14:35 UTC, norbertschuler requested changes
Please rebase on `develop`.

2022-03-16 06:49 UTC, ankitecd requested changes
Also document this whole component

2022-03-16 06:49 UTC, ankitecd commented on src/features/common/Layout/UserLayout/UserLayout.tsx
> +           if (subMenuItem && typeof subMenuItem !== 'undefined') {
First condition also checks if the the property is `undefined` or not. How does the second condition works here?

2022-03-16 06:49 UTC, ankitecd commented on src/features/common/Layout/UserLayout/UserLayout.tsx
> +              <>
I don't think there is need to have fragment as there is only one component i.e `NavLink`

2022-03-16 06:49 UTC, ankitecd commented on src/features/common/Layout/UserLayout/UserLayout.tsx
> +        className={`${styles.navlink} ${activeLink === link.path && typeof activeLink !== 'undefined' ? styles.navlinkActive : ''
Here you can have condition as `activeLink && activeLink === link.path ? <code> :<code>`

2022-03-17 06:05 UTC, ankitecd requested changes
- [ ] Here the parent should also be active, if any one child is active.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/25547888/158747157-f8e76adb-13c2-4ea2-874b-1cb0637492c7.png">

2022-03-17 10:27 UTC, ankitecd approved these changes
Looks good

2022-03-17 10:28 UTC, merged