edited terms & condition feature
Plant-for-the-Planet-org/planet-webapp pull request #1455
Opened 2022-03-22 05:39 UTC by sunilsabatp

Fixes #

Changes in this pull request:
- added feature of Terms and condition
-
-

@

2022-03-24 15:28 UTC, mariahosfeld commented
@sunilsabatp Please also include the German translations of the new text components, at the moment it is only in English (same for the error message, not included in the screenshot).
![translation_problem](https://user-images.githubusercontent.com/84912474/159951660-841c828d-83e3-47cb-81e7-96ebf9097dcb.png)

2022-03-24 20:46 UTC, norbertschuler commented on public/static/locales/en/editProfile.json
> +  "termAndConditionPart1":"I agree to the",
From the perspective of a translator this is difficult and using one resource with a link placeholder would be better. But I am not sure if we use i18n already in a way to support this e.g. with a Trans component.

2022-03-26 17:01 UTC, norbertschuler commented
- [ ] The red error message already gets displayed when you switch e.g. the private checkbox: 

![image](https://user-images.githubusercontent.com/1532418/160249722-4e59cfa7-40fd-40aa-bcd7-eb141e3ed011.jpeg)

And after registration a red error popped up, but I don't have a console on my phone browser to see the related error:

![image](https://user-images.githubusercontent.com/1532418/160249792-699bdeed-8f3a-4313-98c2-83e7b4a4897d.jpeg)

2022-03-26 17:41 UTC, norbertschuler commented
- [ ] And after registration a red error popped up and this new user cannot access its own profile - the API call POST https://app-staging.plant-for-the-planet.org/app/profile to register the user replied with an 400 error:

```
{"code":400,"message":"Validation Failed","errors":{"errors":
   ["Dieses Formular sollte keine zus\u00e4tzlichen Felder enthalten.","","Extra fields: terms"],
"children":{"type":{},"oAuthAccessToken":{},"name":{},"gender":{},"title":{},"firstname":{},"lastname":{},"address":{},"zipCode":{},"city":{},"country":{},"isPrivate":{},"getNews":{},"currency":{},"locale":{},"url":{},"urlText":{},"bio":{},"target":{},"imageFile":{},"tin":{},"mayContact":{}}}}
```

![160249792-699bdeed-8f3a-4313-98c2-83e7b4a4897d](https://user-images.githubusercontent.com/1532418/160251036-03d4214c-5a9b-44c7-a885-53753a81ee64.jpeg)

2022-03-30 07:10 UTC, tejassonar approved these changes

2022-04-02 09:38 UTC, norbertschuler requested changes

2022-04-02 09:38 UTC, norbertschuler commented on src/features/user/CompleteSignup/index.tsx
> +                >
Maybe this link should get opened in a new tab by adding `rel="noopener noreferrer"` and `target={'_blank'}`?

2022-04-02 09:59 UTC, norbertschuler commented on public/static/locales/en/editProfile.json
> +  "termAndConditionPart1":"I agree to the",
Change this towards using the i18n Trans component to support links.

2022-04-02 10:01 UTC, norbertschuler commented
> Please implement interpolation of translation key, so multiple translation keys aren't added for one sentence.

I added a usage of the Trans component from react-i18next: https://react.i18next.com/latest/trans-component.

2022-04-02 10:01 UTC, norbertschuler approved these changes

2022-04-02 10:45 UTC, norbertschuler approved these changes

2022-04-04 10:42 UTC, sagararyal approved these changes

2022-04-04 10:42 UTC, merged