New Message and Error for Delete Profile
Plant-for-the-Planet-org/planet-webapp pull request #1563
Opened 2022-09-07 14:48 UTC by prachigarg19

Fixes #

Check this list and then dismiss it:
- **Localization**
  - Have you added translation resources?
  - Have you localized numbers, dates and other stuff?
- **Validation and error management**
  - Is the user input validated?
  - Is the API response valided and are error responses properly handled?
  - Are errors caught if necessary?
- **Coding style**
  - Have you used a specific type for declaring the properties and parameters instead of `any`?
  - Have you defined interfaces for new components?
  - Have you added a source file not using TypeScript?
  - Have you checked if your newly introduced modules or functions are not already existing?
  - Is your `React.useEffect` using the right dependencies?
  - Check your code if it matches the existing code formatting.

Changes in this pull request:
-
-
-

@

2022-09-08 06:25 UTC, mariahosfeld commented
- [ ] Please change the wording of "Before proceeding, make sure you've deleted all subscriptions before ." to "Before proceeding, make sure you've cancelled all subscriptions."

2022-09-08 09:34 UTC, mariahosfeld commented
The basic functionality works, but please make the error message when a Subscription is still there more prominent, e.g. in red and bold type, so that the user will spot it immediately.

2022-09-10 13:11 UTC, norbertschuler reviewed
LGFM, first I was puzzled if "continue" means continue to delete my profile anyway, but then reading the text I understood continue to be redirected to the subscriptions to be able to cancel them. Maybe the button could be renamed to "show my subscriptions"?

2022-09-12 08:45 UTC, mariahosfeld commented
Functionality works as expected for me.

2022-09-12 13:00 UTC, Shreyaschorge requested changes
Functionally it works. There are only minor changes that needs to be handled.

2022-09-12 13:00 UTC, Shreyaschorge commented on src/features/common/Layout/CustomModal/index.tsx
> +            onClick={onClick1}
@prachigarg19 Please give it a meaningful name, maybe something like `handleContinue`

2022-09-12 13:00 UTC, Shreyaschorge commented on src/features/user/Settings/DeleteProfile.tsx
> +        if (res == 400) {
@prachigarg19 There could be multiple factors that might result into a 400 response. Before opening the Cancel Subscriptions modal, along with 400 response please check the response (i.e error_code, error_type) returned from the server. 
![image](https://user-images.githubusercontent.com/37466979/189659478-62a8801a-35bd-4cd1-99c8-a1b031ad2261.png)

2022-09-12 13:00 UTC, Shreyaschorge commented on src/features/common/Layout/CustomModal/index.tsx
> +            onClick={onClick2}
@prachigarg19 Please give it a meaningful name, maybe something like `handleCancel`

2022-09-14 05:33 UTC, Shreyaschorge approved these changes
LGFM. Only thing is we need to manage our errors in a better way.

2022-09-14 06:41 UTC, merged