Feature/new route redeem code
Plant-for-the-Planet-org/planet-webapp pull request #1568
Opened 2022-09-16 06:08 UTC by sunilsabatp

to do -> create a new route to handle redeem

steps: 
1.use the route `/profile/redeem/:code` to see the result

2022-09-16 06:09 UTC, sagararyal commented
#### 📝 Changed routes:


| [**/profile/redeem/\[code\]**](https://planet-webapp-bahoyn160-planetapp.vercel.app/profile/redeem/[code]) |
|:-:|
|<a href="https://planet-webapp-bahoyn160-planetapp.vercel.app/profile/redeem/[code]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/GG23GFCg89f4lRTZBmaCVbwCXa9iLHeZ7YgGwFTDl5ZFQtHVtjL0TpT1IzPJbif8BPUt32jcseTPgaNERcg5oA.png&w=600" alt="Screenshot of /profile/redeem/[code]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/1tlbYp2akt0DKtj4abjybM1unjdl8ymAS4ZP8zpcEHj88-8qcU4BN4jAA3MaxdoasWWIP6tlnM0x-I_hEriHxA.png">(view full size)</a> |







Commit 40bd3e29371211c74fd2f98fd9e27e5cb4e56706 (https://planet-webapp-bahoyn160-planetapp.vercel.app).

2022-09-20 10:46 UTC, mariahosfeld requested changes
Route works, but the following changes are needed:
- [x] Make sure that new tree count is shown automatically, currently a refresh is needed
- [ ] Provide option to redeem another code in each modal (successfully, already redeemed, invalid)

2022-09-20 11:05 UTC, sunilsabatp commented
> Route works, but the following changes are needed:
> 
> * [ ]  Make sure that new tree count is shown automatically, currently a refresh is needed
> * [ ]  Provide option to redeem another code in each modal (successfully, already redeemed, invalid)

the first issue have been fixed in one of my pr  i.e redeem end point

2022-09-23 07:11 UTC, mariahosfeld commented
Functionality works for me

2022-09-25 09:26 UTC, norbertschuler commented
If this PR replaces #1554 (which I then just unnecessarily tested :-() please close the outdated PR.

2022-09-28 05:03 UTC, mohitb35 commented
> If this PR replaces #1554 (which I then just unnecessarily tested :-() please close the outdated PR.

@norbertschuler This PR is in addition to #1554 - #1554 updates the redemption process from the profile via the RedeemModal, and this PR focuses on a route to directly redeem a code.

2022-10-03 10:07 UTC, norbertschuler commented
I would prefer upgrading `package-lock.json` only in the PR has changed `package.json` or do upgrades in separate PR's which then check if all modules still work well.

2022-10-12 04:38 UTC, prachigarg19 commented on pages/claim/[type]/[code].tsx
> +  }, [router, router.query.type, ready]);
Why do we need router and router.query.type both as dependencies here?

2022-10-12 05:50 UTC, prachigarg19 approved these changes

2022-10-12 07:18 UTC, mariahosfeld commented
> * [ ]  Using some random url as https://planet-webapp-hxl3eqtui-planetapp.vercel.app/claim/test/xxx-xxx results into some endless spinner (wasn't working well before):
> 
> 
> <img alt="Bildschirmfoto 2022-10-03 um 12 15 11" width="442" src="https://user-images.githubusercontent.com/1532418/193554301-8427cf05-48a1-48a1-a1cf-a2e7684b2673.png">

This has been solved, will now result in "invalid code" message.

2022-10-12 07:21 UTC, merged