Updates for Planet Cash
Plant-for-the-Planet-org/planet-webapp pull request #1571
Opened 2022-09-19 09:33 UTC by mohitb35

Changes
1. Remove planet cash account activation / deactivation functionality
2. Prevent account creation from front end if a planet cash account already exists.
3.

2022-09-19 10:50 UTC, sagararyal commented
#### 📝 Changed routes:


| [**/profile/planetcash**](https://planet-webapp-63stss32v-planetapp.vercel.app/profile/planetcash) |
|:-:|
|<a href="https://planet-webapp-63stss32v-planetapp.vercel.app/profile/planetcash"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/T0sWN1nLXeV369eeHywbgA0XY9hTmf21LxfKm4UHOvKtRTpCtPqlzDFr2-Uy-pj_GMjmgBOY3sJEO9rP3GEzjQ.png&w=600" alt="Screenshot of /profile/planetcash" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/wpinJnocnz7XuGzdfFIbMTK8KAPyKCf7NCXzzyY2_3i-07cT86K7UftGaumRbRURGlBh-Wy3c3VhJZUBCXiZUg.png">(view full size)</a> |







Commit e0bf4081b1fcccc5d61cbcfb46c0c342ec350b2a (https://planet-webapp-63stss32v-planetapp.vercel.app).

2022-09-19 13:29 UTC, mariahosfeld commented
Most of the functionality works for me, but sometimes when no PlanetCash account exists, I do not see the create form, I see nothing. Refresh solves this then, but here a screenshot:
![grafik](https://user-images.githubusercontent.com/84912474/191028410-45c3bcbb-05d8-41b6-926e-e694ad5c641f.png)
Unable to identify anything in my console logs (I see only 200).

2022-09-20 05:13 UTC, mohitb35 commented
> Most of the functionality works for me, but sometimes when no PlanetCash account exists, I do not see the create form, I see nothing. Refresh solves this then, but here a screenshot: ![grafik](https://user-images.githubusercontent.com/84912474/191028410-45c3bcbb-05d8-41b6-926e-e694ad5c641f.png) Unable to identify anything in my console logs (I see only 200).

This is fixed. The issue occurred because the redirect was happening only after fetching accounts, and accounts are not fetched again after setting them in the context. So when you click on My Planetcash in the menu multiple times, this issue occurred.

2022-09-20 09:32 UTC, mariahosfeld commented
Functionality works as expected.

2022-09-20 18:37 UTC, prachigarg19 commented
@mohitb35 I was wondering if we could change the StyledTabs orientation to "horizontal" and make respective changes in styling for smaller screens. 
Current view: 
![image](https://user-images.githubusercontent.com/72646230/191337527-63d14d82-a8ef-4b8b-85d1-d4f3d26ce8ba.png)
Maybe we could go for something like this: 
![image](https://user-images.githubusercontent.com/72646230/191337650-d2e3bffa-fc9d-47b5-aaa5-24b8b8fb7528.png)

2022-09-21 15:58 UTC, prachigarg19 commented
@mohitb35 When I try to go to planetcash/new with a PCA already created, I'm redirected to /planetcash but in this process I receive this warning in console.  

![image](https://user-images.githubusercontent.com/72646230/191552988-999887be-40ce-440c-a991-84c3bf4eab8f.png)

2022-09-21 16:21 UTC, prachigarg19 requested changes
Functionality works for me as well.

2022-09-21 20:03 UTC, mohitb35 commented on src/features/user/PlanetCash/screens/Accounts.tsx
>        {accounts?.map((account, index) => {
There can be multiple planet cash accounts. The restriction on creation is only on the front end. Multiple accounts are possible to create from the backend.

2022-09-22 05:03 UTC, mohitb35 commented
> @mohitb35 I was wondering if we could change the StyledTabs orientation to "horizontal" and make respective changes in styling for smaller screens. Current view: ![image](https://user-images.githubusercontent.com/72646230/191337527-63d14d82-a8ef-4b8b-85d1-d4f3d26ce8ba.png) Maybe we could go for something like this: ![image](https://user-images.githubusercontent.com/72646230/191337650-d2e3bffa-fc9d-47b5-aaa5-24b8b8fb7528.png)

@prachigarg19 This could be considered as a future enhancement

2022-09-22 07:14 UTC, mohitb35 commented
> @mohitb35 When I try to go to planetcash/new with a PCA already created, I'm redirected to /planetcash but in this process I receive this warning in console.
> 
> ![image](https://user-images.githubusercontent.com/72646230/191552988-999887be-40ce-440c-a991-84c3bf4eab8f.png)

Fixed in https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1571/commits/eaa296a8e3f88c5fbd500d0284ef158914d676c5

2022-09-22 10:05 UTC, merged