feature/home logo
Plant-for-the-Planet-org/planet-webapp pull request #1666
Opened 2023-01-27 06:57 UTC by sunilsabatp

feature->changed the home logo for all tenants except salesforce

2023-01-29 15:41 UTC, norbertschuler commented
I think the new logo does not fit with the line width of the drawings of other menu items.

2023-02-05 12:13 UTC, norbertschuler approved these changes
Technically this pull requests works, but I think HomeLogoSelected does not fit to the design of the other icons.

2023-02-08 06:56 UTC, mohitb35 requested changes
1. Icons need to be updated to match styles of other items.
2. I think the HomeLogo and HomeLogoSelected icons have been interchanged by mistake.

2023-02-08 06:56 UTC, mohitb35 commented on public/assets/images/navigation/HomoLogo.tsx
> +function HomeLogo() {
Accept a color prop for HomeLogo

2023-02-08 06:56 UTC, mohitb35 commented on src/features/common/Layout/Navbar/getNavBarIcon.tsx
> +          <HomeLogo />
Pass color as a prop for HomeLogo similar to how is done for other icons.

2023-02-08 06:56 UTC, mohitb35 commented on src/features/common/Layout/Navbar/getNavBarIcon.tsx
> +          <HomeLogo />
Nested ternary conditions are difficult to read later on. Can this be simplified (perhaps extract some of this logic into a separate function).

2023-02-08 06:56 UTC, mohitb35 commented on src/features/common/Layout/Navbar/getNavBarIcon.tsx
> +          <HomeLogo />
1. Nested ternary conditions are difficult to read later on. Can this be simplified (perhaps extract some of this logic into a separate function).
2. Pass color as a prop for HomeLogo similar to how is done for other icons.

2023-02-08 06:56 UTC, mohitb35 commented on public/assets/images/navigation/HomeLogoSelected.tsx
> +      width="24"
I'd suggest checking out the other navigation icons. They differ in viewbox (most have a height of 512 defined in the viewbox i.e. viewBox="0 0 widthValue 512), and no height/width is explicitly provided. Not defining dimensions within this component itself makes the dimensions easier to manipulate via code (if needed).

2023-02-08 06:56 UTC, mohitb35 commented on public/assets/images/navigation/HomoLogo.tsx
> +      viewBox="0 0 255.12 255.12"
I'd suggest checking out the other navigation icons. They differ in viewbox (most have a height of 512 defined in the viewbox i.e. viewBox="0 0 widthValue 512), and no height/width is explicitly provided. Not defining dimensions within this component itself makes the dimensions easier to manipulate via code (if needed).

2023-02-28 08:21 UTC, mariahosfeld commented
Looks good to me, asked more stakeholders for their feedback.

2023-05-08 09:51 UTC, mariahosfeld commented
This version looks good to me.

2023-05-08 12:18 UTC, mohitb35 commented on public/tenants/planet/config.ts
> +      // },
Don't forget to remove this

2023-05-08 12:30 UTC, mohitb35 approved these changes

2023-05-08 12:30 UTC, mohitb35 commented on public/tenants/planet/config.ts
> +      // },
Don't forget to remove this.

2023-05-08 12:31 UTC, merged