refactor: project creation
Plant-for-the-Planet-org/planet-webapp pull request #1704
Opened 2023-03-15 11:47 UTC by sunilsabatp

refactor -> ordering the components of project creation

2023-03-15 11:47 UTC, sagararyal commented
#### 📝 Changed routes:


| [**…e/projects/new-project**](https://planet-webapp-oyv4oymm3-planetapp.vercel.app/profile/projects/new-project) |
|:-:|
|<a href="https://planet-webapp-oyv4oymm3-planetapp.vercel.app/profile/projects/new-project"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/e5rewwPa9UmVuLLGGKM9I7Kz-6Q2TKdLq-3v_ArWDvhQOKffYCNsbceAYHcyUXV8c1wHgINAGM2ZF7MycFS-ug.png&w=600" alt="Screenshot of /profile/projects/new-project" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/7UnbUjQ4p2pTyUTpQXSQsif12XoOlifQhMVLsSCD1-mh6IBbGcP6W6qmuDvvAHWhKHwIbEuNuUx4Uo4Dm-qoRg.png">(view full size)</a> |







Commit 0b526c292d5937c05e221239f0edeb2402e25e6c (https://planet-webapp-oyv4oymm3-planetapp.vercel.app).

2023-03-25 11:08 UTC, norbertschuler commented
- [ ] Trying to created a conservation project get stuck on the project media screen showing the error of the screen shot if you try to go back or skip while save & continue does nothing.

<img width="1120" alt="Bildschirm­foto 2023-03-25 um 12 06 32" src="https://user-images.githubusercontent.com/1532418/227713922-9dc5628c-bb6d-42cc-bd1b-ab1dd98590b1.png">

2023-03-25 11:11 UTC, norbertschuler commented
- [ ] the continue button on any section does not seem to work properly

2023-03-26 10:14 UTC, sunilsabatp commented
> * [ ]  Trying to created a conservation project get stuck on the project media screen showing the error of the screen shot if you try to go back or skip while save & continue does nothing.
> 
> <img alt="Bildschirm­foto 2023-03-25 um 12 06 32" width="1120" src="https://user-images.githubusercontent.com/1532418/227713922-9dc5628c-bb6d-42cc-bd1b-ab1dd98590b1.png">

I'm going to look into it

2023-03-28 13:18 UTC, mariahosfeld commented
Please compare the size of the used buttons (and arrow elements) to other sections that have already been updated. The sizing seems to be a bit off, as the buttons are quite large.

2023-04-01 08:27 UTC, norbertschuler approved these changes
I just tested the basic workflow (not every edge case) and it seems to work.

2023-04-01 08:27 UTC, norbertschuler commented on src/features/user/ManageProjects/components/ProjectSpending.tsx
> +                setErrorMessage('Please upload  report');
Do we want some translated error here?

2023-04-03 09:45 UTC, mariahosfeld commented
- [ ] On "Basic Details" the last toggle switch is missing/not visible.
- [ ] Fields for coordinates on map on "Basic Details" are out of alignment.
- [ ] Fields for coordinates should not be transparent, very hard to read.
- [ ] Layout indicating helper text on "Detailed Analysis" does not look good, try an opaque background to avoid it looking like crossed out
![grafik](https://user-images.githubusercontent.com/84912474/229473123-5e8f405f-87df-4f9d-aa35-35c478803481.png)
- [ ] Bug: Switching the language while creating/editing a project does not change all translations, refresh is needed
- [ ] Review page needs to be updated.

2023-04-26 09:42 UTC, mohitb35 commented
I see a client side exception after clicking the edit button on a project.

<img width="1440" alt="Screenshot 2023-04-26 at 3 11 49 PM (2)" src="https://user-images.githubusercontent.com/44917347/234536934-ae0900f6-0981-4130-bd3e-2acdac8584ce.png">

![Screenshot 2023-04-26 at 3 11 49 PM](https://user-images.githubusercontent.com/44917347/234536906-96776830-2b26-4c80-a8d5-0ff9b8fbda21.png)

2023-04-26 09:48 UTC, mohitb35 requested changes
I see a client side exception after clicking the edit button on a project. The same happens while trying to create a new project as well.

![Screenshot 2023-04-26 at 3 14 11 PM](https://user-images.githubusercontent.com/44917347/234537538-647a538e-e57e-42d4-8415-d7e91e61a789.png)

2023-05-02 09:56 UTC, mariahosfeld requested changes
- [x] Facing capitalization issue on the buttons, should be shown as it is in the ressource
Example English (should be `Back to basic details`)
![grafik](https://user-images.githubusercontent.com/84912474/235636143-96618b18-3aa0-4727-821a-5270f34449e4.png)
Example German (should be `Zurück zu den grundlegenden Details`)
![grafik](https://user-images.githubusercontent.com/84912474/235636326-cd53dd78-6127-4c23-869c-f802b52221de.png)
- [ ] Font size: Depending on the language, the description text in some input fields is too long
Example German
![grafik](https://user-images.githubusercontent.com/84912474/235645715-411054f2-17da-4982-bab8-7b2602ed90aa.png)
- [ ] Changing the language does not manifest immediately in all places, e.g. the lables of the `Site Owner` options

2023-05-04 06:31 UTC, sunilsabatp commented
> * [ ]  Facing capitalization issue on the buttons, should be shown as it is in the ressource
>   Example English (should be `Back to basic details`)
>   ![grafik](https://user-images.githubusercontent.com/84912474/235636143-96618b18-3aa0-4727-821a-5270f34449e4.png)
>   Example German (should be `Zurück zu den grundlegenden Details`)
>   ![grafik](https://user-images.githubusercontent.com/84912474/235636326-cd53dd78-6127-4c23-869c-f802b52221de.png)
> * [ ]  Font size: Depending on the language, the description text in some input fields is too long
>   Example German
>   ![grafik](https://user-images.githubusercontent.com/84912474/235645715-411054f2-17da-4982-bab8-7b2602ed90aa.png)
> * [ ]  Changing the language does not manifest immediately in all places, e.g. the lables of the `Site Owner` options

this issue is covered under this [https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1748](PR)

2023-05-08 10:36 UTC, mohitb35 commented on src/features/user/ManageProjects/StepForm.module.scss
Remove styles that are no longer used. For example, `.mainContainer` and `.stepContainer`

2023-05-08 10:39 UTC, mohitb35 commented
@sunilsabatp 
1. Check that the handleNext / handleBack functionality is working correctly.
2. Add proper types to the main component props and address TS warnings.

2023-05-09 07:30 UTC, sunilsabatp commented on pages/profile/projects/new-project.tsx
> +                <span>{t('manageProjects:supportLink')}</span>
@mariahosfeld what's your view point about the second point ?

2023-05-10 02:41 UTC, sunilsabatp commented on pages/profile/projects/new-project.tsx
> +                <span>{t('manageProjects:supportLink')}</span>
I'm also not sure about support link, I'll conform it from @mariahosfeld

2023-08-11 06:28 UTC, mohitb35 commented
@mariahosfeld @sunilsabatp I've made a few changes and this PR is ready to review.

2023-08-11 07:20 UTC, mariahosfeld commented
Maybe it is just my browser, but on the basic details page, at the beginning of the lon and lat input fields I have gaps in the frame
![image](https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/84912474/9af263ef-3dc8-4c80-b56b-335b209ac09f)

2023-08-11 07:38 UTC, mariahosfeld commented
One other thing: Please move the field for Long Term Plan up, so it is above the field for the Site Owner. This is for both, restoration and conservation problems.
Other than that everything worked fine.

2023-08-13 16:23 UTC, sunilsabatp commented on src/features/user/ManageProjects/StepForm.module.scss
> +} */
could you pls clean it up, if it is not needed ?

2023-08-21 15:34 UTC, mariahosfeld approved these changes

2023-08-22 09:25 UTC, mohitb35 approved these changes

2023-08-22 09:30 UTC, merged