Component unification (Edit profile page)
Plant-for-the-Planet-org/planet-webapp pull request #1712
Opened 2023-03-27 18:05 UTC by prachigarg19

Unify mui components in the webapp.

2023-04-08 08:57 UTC, norbertschuler approved these changes

2023-04-18 11:10 UTC, prachigarg19 commented
The layout breaks for empty inputs:
![image](https://user-images.githubusercontent.com/72646230/232759574-b8b9f736-e2ed-45bc-9cad-99b606d080f1.png)

2023-04-18 11:11 UTC, prachigarg19 commented
> The layout breaks for empty inputs: ![image](https://user-images.githubusercontent.com/72646230/232759574-b8b9f736-e2ed-45bc-9cad-99b606d080f1.png)

Dealt with in latest commit.

2023-04-19 06:18 UTC, mohitb35 requested changes
@prachigarg19 Please go through my feedback.

2023-04-19 06:18 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
> +  const saveProfile = async (data: object) => {
Avoid using `object` or similar generic types. In this case, you could define the type of data submitted by the form.

2023-04-19 06:18 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
> +          />
Resolve the TS warnings seen here.

2023-04-19 06:18 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
> +              disabled
are both of these needed?

2023-04-19 06:18 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
I see a few warnings in the browser console while running this locally. Try to resolve these. 

```
MUI: The value provided to Autocomplete is invalid. None of the options match with `{"id":"","title":"","value":""}`.
```
```
getNews is missing in the 'defaultValue' prop of either its Controller (https://react-hook-form.com/api#Controller) or useForm (https://react-hook-form.com/api#useForm) 
```
```
isPrivate is missing in the 'defaultValue' prop of either its Controller (https://react-hook-form.com/api#Controller) or useForm (https://react-hook-form.com/api#useForm) 
```

2023-04-19 06:18 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
>          ) : null}
You could also use the `<ReactHookFormSelect>` component that is used in BankDetailsForm and PayoutScheduleForm.

2023-04-19 06:22 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
> +          <MuiAutoComplete
You could also use <ReactHookFormSelect> over here, as used in BankDetailsForm / PayoutScheduleForm, if you want to make this available to ReactHookForm.

2023-05-03 04:43 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/index.tsx
> +    <DashboardView title={t('editProfile')} subtitle={null} type="other">
Created a separate issue #1758 for later

2023-05-03 04:53 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
>            <div style={{ width: '20px' }}></div>
Is this needed any more?

2023-05-03 04:55 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
>      React.useContext(UserPropsContext);
You seem to have reintroduced some deleted code while merging conflicts.

2023-05-03 05:00 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
> +            render={(props: object) => (
There are TS warnings seen here as `props` has been typed as an object

2023-05-03 05:00 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
I still see some warnings relating to the code added that could be resolved.

2023-05-03 05:06 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
> +  type?: string;
`type` should not be included within `FormData` as the field providing this is not registered with react hook form. In `saveProfile` we get the value for `type` from state, not from form data.

2023-05-03 05:07 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
> +          />
This is pending

2023-05-03 05:09 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
>          ) : null}
Left as is as this needs a greater refactor to the code of the `ReactHookFormSelect` component to make it more generic.

2023-05-03 05:09 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/EditProfileForm.tsx
> +          <MuiAutoComplete
Left as is as this needs a greater refactor to the code of the `ReactHookFormSelect` component to make it more generic.

2023-05-04 11:27 UTC, mohitb35 approved these changes
LGTM

2023-05-04 11:31 UTC, merged