Feature/impersonation with support pin
Plant-for-the-Planet-org/planet-webapp pull request #1721
Opened 2023-03-31 06:29 UTC by sunilsabatp

Feature -> added new field for impersonation form (i.e support pin)

2023-04-03 08:13 UTC, mariahosfeld commented
Functionality is looking good so far.

2023-04-03 08:19 UTC, mariahosfeld commented
Issue: The link to select the language is also present for "support pin", it needs to be removed there.

2023-04-12 07:01 UTC, mariahosfeld commented
Functionality looks good to me.

2023-04-17 10:13 UTC, mariahosfeld reviewed
Functionality works for me.

2023-04-17 10:18 UTC, mohitb35 requested changes
@sunilsabatp Please review my feedback.

2023-04-17 10:18 UTC, mohitb35 commented on src/utils/apiRequests/api.ts
> +  impersonatedData?:ImpersonationData
Be consistent about naming things. `impersonationData` or `impersonatedData`?

2023-04-17 10:18 UTC, mohitb35 commented on src/utils/apiRequests/api.ts
> +  const  impersonatedDataFromLocal = JSON.parse(targetData);
You can probably combine these 2 lines. Don't forget to check for TS warnings - JSON.parse expects a string.

2023-04-17 10:18 UTC, mohitb35 commented on src/utils/apiRequests/api.ts
> +  }
You could abstract this logic to a common function as it used in all authenticated requests.

2023-04-17 10:18 UTC, mohitb35 commented on src/features/common/Layout/UserLayout/UserLayout.tsx
> +              localStorage.removeItem('impersonatedData');
Be consistent with naming. Here you should remove `impersonationData` not `impersonatedData`

2023-04-17 10:39 UTC, mohitb35 commented on src/features/common/Layout/UserLayout/UserLayout.tsx
> +        setSupportPin(response?.supportPin);
When this is updated, you should maintain a sync with the user object in UserPropsContext.

2023-04-19 06:31 UTC, mariahosfeld commented
Please make sure that

- [ ] The color of the refresh icon changes to green as well
- [ ] The user is informed about the purpose of the refresh icon by adding a title "get new pin"

2023-04-20 07:19 UTC, mohitb35 commented on src/features/common/Layout/UserLayout/UserLayout.tsx
> +              localStorage.removeItem('impersonatedData');
This is missed out.

2023-04-20 10:51 UTC, mohitb35 requested changes

2023-04-20 10:59 UTC, mohitb35 approved these changes

2023-04-20 11:06 UTC, merged