Modifications to Top/Verified projects
Plant-for-the-Planet-org/planet-webapp pull request #1774
Opened 2023-05-12 10:13 UTC by prachigarg19

1. Replace top project badge

2023-05-15 14:15 UTC, mariahosfeld requested changes
- [x] Check for the padding on the right side, the project name should break at the same point where the Top Project badge ends
![grafik](https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/84912474/8a039f61-8037-44f5-807d-62fa22a57f6d)
- [ ] Pop-up on hover is not visible

2023-05-23 11:32 UTC, mariahosfeld commented
- [ ] The link in the pop-up on hover over top project badge is not working correctly.

2023-05-23 11:32 UTC, mariahosfeld commented
The rest is looking good functionality wise.

2023-05-24 05:22 UTC, mohitb35 commented on src/features/projects/components/ProjectSnippet.tsx
> +          <>
1. Please separate the top project badge into a different component.
2. The figma design seems to have changed slightly. @mariahosfeld could you confirm this? Should those changes be made here as well?
3. I think the border on the top project badge can be removed. It isn't in the current figma design as well.
<img width="357" alt="Screenshot 2023-05-24 at 10 51 11 AM (2)" src="https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/44917347/1d0963f1-3ac9-4bd3-87f3-6295bdabaac0">

2023-05-24 05:25 UTC, mohitb35 commented on src/features/projects/components/ProjectSnippet.tsx
> +  const popupState1 = usePopupState({
Avoid using names like `popupState1` and `popupState2`. It would be clearer if you identified the popup with the name e.g. `verifiedPopupState`

2023-05-24 06:09 UTC, mohitb35 requested changes
@prachigarg19 Please go through these comments as well

2023-05-24 06:09 UTC, mohitb35 commented on src/features/projects/styles/ProjectSnippet.module.scss
>  }
While this works, if I were to do somethign like change the font size for the project name, I'd end up needing to make adjustments here as well. It also has the effect of leaving a left margin if the verified icon ends up on a new line for any reason.

Refer this for a possible alternative approach - https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1787/commits/40cd858eba669e966310c09f84985967b2ac3d0d

2023-05-24 06:09 UTC, mohitb35 requested changes
@prachigarg19 Please go through these comments as well

2023-05-24 06:12 UTC, mohitb35 commented on src/features/projects/components/PopupProject.tsx
See if a common component can be used for the Top Project and Verified Badge here as well. You would just need to conditionally allow or disable the popovers.

2023-05-24 12:09 UTC, prachigarg19 commented on src/features/projects/styles/ProjectSnippet.module.scss
> +  padding-right: 16px;
https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1774#pullrequestreview-1426671258
Padding had to be added to project name

2023-05-25 06:19 UTC, mohitb35 approved these changes
Made minor changes, LGTM now

2023-05-25 06:19 UTC, mohitb35 commented on src/features/projects/components/TopProjectBadge.tsx
> +  displayPopup: Boolean;
Fixed in 9c9280a57abe3ce2ec6bea14e399bd511d4a7b85

2023-05-25 06:19 UTC, mohitb35 commented on src/features/projects/components/VerifiedBadge.tsx
> +    popupId: 'demoVerifiedPopover',
Fixed in 9c9280a57abe3ce2ec6bea14e399bd511d4a7b85

2023-05-25 06:19 UTC, mohitb35 commented on src/features/projects/components/TopProjectBadge.tsx
> +    popupId: 'demoTopProjectPopover',
Fixed in 9c9280a57abe3ce2ec6bea14e399bd511d4a7b85

2023-05-25 06:19 UTC, mohitb35 commented on src/features/projects/styles/ProjectSnippet.module.scss
>  }
I made minor changes in 271b26be9f7221520a51cd57bb8eba03634b0da4

2023-05-25 06:25 UTC, mariahosfeld approved these changes

2023-05-25 06:25 UTC, merged