Resolve TS errors: TreeMapper
Plant-for-the-Planet-org/planet-webapp pull request #1860
Opened 2023-09-06 18:19 UTC by prachigarg19

This PR resolves typescript errors

2023-09-12 05:11 UTC, mohitb35 commented
@prachigarg19 Please resolve conflicts. Is this otherwise complete, or is anything left?

2023-09-13 11:28 UTC, prachigarg19 commented
> @prachigarg19 Please resolve conflicts. Is this otherwise complete, or is anything left?

It's complete

2023-09-21 05:17 UTC, mohitb35 reviewed
test

2023-09-22 06:16 UTC, mohitb35 requested changes
@prachigarg19 Please go through my feedback

2023-09-26 08:06 UTC, prachigarg19 commented on src/features/user/TreeMapper/components/TreeMapperList.tsx
>    isDataLoading: boolean;
Yes, properties match with `PlantLocation` in `plantLocation.d.ts`.

2023-09-27 04:41 UTC, mohitb35 commented on src/features/user/TreeMapper/index.tsx
> +                  location.sampleTrees = [];
The `&& 'sampleTrees' in location` condition was removed as it made the code in the `if` block unreachable.

2023-09-27 04:53 UTC, mohitb35 commented on src/features/user/TreeMapper/Import/components/SampleTrees.tsx
> +            const sampleTrees: SampleTree[] = resultsData.map((sampleTree) => {
Have created an issue #1872 relating to the CSV validation and the pending warning `Type 'unknown[]' is not assignable to type 'SampleTree[]'` seen for `resultsData`.

2023-09-27 05:27 UTC, mohitb35 approved these changes
LGTM now.

2023-09-27 05:34 UTC, merged