Resolve TS errors: ManageProjects
Plant-for-the-Planet-org/planet-webapp pull request #1871
Opened 2023-09-21 16:05 UTC by prachigarg19

This PR resolves ts errors for all files in` ManageProjects`

2023-09-22 11:45 UTC, mohitb35 requested changes
@prachigarg19 Some minor changes suggested, but there are 2 components which seem to have been left alone: `MapComponent` and `ProjectSites`. Could you address the TS warnings there too?

2023-09-22 11:45 UTC, mohitb35 commented on src/features/user/ManageProjects/components/ProjectMedia.tsx
While fetching images for the project, you're using the `Project` type. I think this should be handled similar to `ProjectCertificates` - where you've defined a `CertificateScopeProjects` interface.

```
const fetchImages = async () => {
    try {
      // Fetch images of the project
      if (projectGUID && token) {
        const result = await getAuthenticatedRequest<Project>(
```

2023-09-22 11:45 UTC, mohitb35 commented on src/features/common/types/project.d.ts
You've made a change here to `ProjectSitesProps`, but ProjectSites has not been updated (handle other issues over there as well)

2023-09-22 11:45 UTC, mohitb35 commented on src/features/user/ManageProjects/components/ProjectSpending.tsx
While fetching expenses for the project, you're using the `Project` type. I think this should be handled similar to `ProjectCertificates` - where you've defined a `CertificateScopeProjects` interface.

2023-09-22 11:45 UTC, mohitb35 commented on src/features/user/ManageProjects/index.tsx
> +          ? project?.name
The ? check in `project?.name` is redundant

2023-09-25 10:18 UTC, prachigarg19 commented
> @prachigarg19 Some minor changes suggested, but there are 2 components which seem to have been left alone: `MapComponent` and `ProjectSites`. Could you address the TS warnings there too, if they are not being addressed in #1856 ?

@sunil-sabat will be working on `MapComponent`
Error: `Unexpected any. Specify a different type.` was not resolved since currently I'm facing `500` error when I try to save a site.

2023-09-26 12:07 UTC, mohitb35 approved these changes
LGTM

2023-09-26 12:14 UTC, merged