Update email validation
Plant-for-the-Planet-org/planet-webapp pull request #1881
Opened 2023-10-04 13:14 UTC by prachigarg19

Implement zod email validation in place of current validation to obtain a common approach throughout the webapp

2023-10-05 15:53 UTC, mariahosfeld commented
Scope needs to be expanded before release.

2023-10-18 06:11 UTC, mohitb35 requested changes
@prachigarg19 I'm not sure if this PR was ready for review, but it currently does not work.

2023-10-18 06:11 UTC, mohitb35 commented on src/utils/isEmailValid.ts
1. Has 'zod' been imported? I see a warning - Cannot find module 'zod' or its corresponding type declarations.
2. The INVALID_DOMAIN_LIST is not being considered any more.

2023-10-20 09:39 UTC, mohitb35 approved these changes

2023-10-21 08:02 UTC, norbertschuler requested changes

2023-10-21 08:02 UTC, norbertschuler commented on src/utils/isEmailValid.ts
> +import { z } from 'zod';
`zod` is imported only as a dependency from the `next` package in our `package-lock.json`. But I would suggest adding all packages used in our code directly in our `package.json` with `npm add zod` and not rely on it being loaded by some dependency!

2023-10-21 08:17 UTC, norbertschuler commented on src/utils/isEmailValid.ts
> +import { z } from 'zod';
Btw. you did add the package `zod` in https://github.com/Plant-for-the-Planet-org/planet-donations/pull/440 ;-)

2023-10-21 08:20 UTC, norbertschuler commented on src/utils/isEmailValid.ts
> +import { z } from 'zod';
Did that myself now.

2023-10-23 04:55 UTC, mohitb35 approved these changes

2023-10-23 06:31 UTC, merged