Updates text on salesforce home page
Plant-for-the-Planet-org/planet-webapp pull request #1950
Opened 2023-12-21 20:39 UTC by mohitb35

Updates text on salesforce home page, and presents rounded down value for treecounter.

2023-12-28 13:35 UTC, prachigarg19 requested changes

2023-12-28 13:35 UTC, prachigarg19 commented on src/tenants/salesforce/TreeCounter/TreeCounter.module.scss
> +  display: inline-block;
Why is `display: inline-block` used?

2023-12-28 13:35 UTC, prachigarg19 commented on src/tenants/salesforce/TreeCounter/TreeCounter.module.scss
> +  // width: 30px;
Could you remove the comments?

2023-12-28 13:38 UTC, prachigarg19 approved these changes

2024-01-02 09:29 UTC, mariahosfeld approved these changes

2024-01-02 09:29 UTC, merged