Design Forest Fire Popup
Plant-for-the-Planet-org/planet-webapp pull request #1969
Opened 2024-02-02 11:11 UTC by prachigarg19

Component:
<img width="245" alt="image" src="https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/72646230/39d5fd50-ee35-44bd-8fb3-e1cda82fc23a">

2024-03-27 11:08 UTC, gangakhushlani approved these changes

2024-04-17 06:50 UTC, mohitb35 commented
The background for most of the popup is currently transparent.

![Screenshot 2024-04-17 at 12 18 32 PM](https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/44917347/048fba93-a2b5-4b93-870e-c236eb63da2f)

2024-04-17 07:52 UTC, mohitb35 commented on src/temp/FirePopup/index.tsx
> +        </div>
How could you structure the html for `popupContainer` for better semantics?

For example, would a `aside` tag be better than using a `div` for the outermost element? How can you identify the heading/label of this element?

2024-04-17 07:54 UTC, mohitb35 commented on src/temp/FirePopup/index.tsx
Add a comment to indicate that the contents are hardcoded. This component will need to be refactored based on the api/data that is needed.

2024-04-17 07:55 UTC, mohitb35 requested changes
@prachigarg19 Please go through the comments above.

2024-04-18 12:02 UTC, mohitb35 approved these changes

2024-04-18 12:03 UTC, merged