Feature/redesign about section
Plant-for-the-Planet-org/planet-webapp pull request #1973
Opened 2024-02-07 07:29 UTC by prachigarg19

Current implementation:
<img width="245" alt="image" src="https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/72646230/cb4aa0f4-16ae-4253-8aca-c244b0559286">

Before:
<img width="253" alt="image" src="https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/72646230/afd9bf63-993d-44e0-94b2-3983eb601f55">

2024-03-06 08:10 UTC, sunilsabatp commented
Apply ` cursor:pointer` to the button

2024-03-06 08:30 UTC, sunilsabatp commented
"I'm not sure, but it seems like some words have been merged into one.
![image](https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/101264823/903289ad-67b3-4ff6-8ec1-f38b57097db7)

2024-03-14 10:26 UTC, prachigarg19 commented
> Apply ` cursor:pointer` to the button

Are you talking about `See More` button, it already has this property

2024-03-14 10:45 UTC, sunilsabatp approved these changes

2024-03-14 10:45 UTC, sunilsabatp commented on src/temp/AboutSection/AboutProject.tsx
> +    ? splittedText.slice(0, amountOfWords - 1).join(' ')
The logic for splitting the description into "beginText" and "endText" can be a bit convoluted. Consider simplifying it or adding comments to clarify its purpose.

2024-03-27 11:17 UTC, gangakhushlani commented
<img width="584" alt="Screenshot 2024-03-27 at 4 45 45 PM" src="https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/160491167/0e0bb5bb-3f28-4f5f-b603-d6d3d4cc6880">



CTA style is different here in about project box @sunilsabatp

2024-03-27 11:18 UTC, gangakhushlani reviewed
Change "see more" button style

2024-04-15 09:38 UTC, mohitb35 commented on src/temp/AboutSection/AboutProject.tsx
> +        {beginText}{' '}
Add '...' when only the `beginText` is being shown (if there is `endText`)

2024-04-15 09:44 UTC, mohitb35 commented on src/temp/AboutSection/AboutProject.tsx
Logic is fine, but I'd suggest some renaming for clarity.

1. `splittedText` can become `descriptionWords`
2. `amountOfWords` in props could become `wordCount`
3. `itCanOverflow` can become `hasLargeDescription` or `hasOverflow`
4. `beginText` can become `startingText` (begin is an action, so `startingText` indicates the purpose better)

2024-04-15 09:49 UTC, mohitb35 requested changes
@prachigarg19 I've left some minor feedback.

2024-04-15 09:56 UTC, prachigarg19 commented
> Change "see more" button style

Tis design change was suggested by @sagararyal

2024-04-16 09:25 UTC, mohitb35 approved these changes

2024-04-16 09:26 UTC, merged