Time Travel Dropdown
Plant-for-the-Planet-org/planet-webapp pull request #1991
Opened 2024-02-28 13:09 UTC by prachigarg19

New design:
<img width="229" alt="image" src="https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/72646230/11bca5ae-92b6-4a99-aaad-0b5961e22de3">
This PR creates two stories to depict 2 states:
1. Dropdown is closed
2. Dropdown is open

2024-03-05 05:44 UTC, sunilsabatp requested changes

2024-03-05 05:44 UTC, sunilsabatp commented on src/temp/TimeTravelDropdown/TimeTravelDropdown.tsx
> +      >
Using a `<button>` element instead of a` <div>` would be more semantically appropriate for handling click events

2024-03-05 09:40 UTC, sunilsabatp commented
when the drop down is active ,the arrow icon should be  inverted
![image](https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/101264823/67e830ab-68b8-46dc-8006-90b425af7d92)
![image](https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/101264823/d97104fb-d242-4720-95cf-659d8aaead9e)

2024-03-05 10:01 UTC, prachigarg19 commented
> when the drop down is active ,the arrow icon should be inverted ![image](https://private-user-images.githubusercontent.com/101264823/310061619-67e830ab-68b8-46dc-8006-90b425af7d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzMxNzQsIm5iZiI6MTcwOTYzMjg3NCwicGF0aCI6Ii8xMDEyNjQ4MjMvMzEwMDYxNjE5LTY3ZTgzMGFiLTY4YjgtNDZkYy04MDA2LTkwYjQyNWFmN2Q5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMDAxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2FmMzhjYTMzYWVmYzcyMmM1ZWI0ZGJjYzU2NDFkNzNhZDNmOGI0N2NlNDdhMmQ5NTQ0Y2U1M2JlYjE4ZmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JKzxl_KVRMYnMNIYJWv_qn-ZqtXpjv90P944Jvm1tlY) ![image](https://private-user-images.githubusercontent.com/101264823/310061907-d97104fb-d242-4720-95cf-659d8aaead9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzMxNzQsIm5iZiI6MTcwOTYzMjg3NCwicGF0aCI6Ii8xMDEyNjQ4MjMvMzEwMDYxOTA3LWQ5NzEwNGZiLWQyNDItNDcyMC05NWNmLTY1OWQ4YWFlYWQ5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMDAxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDg2ZjBkM2JhM2NjODUyZmExMjg5NzhmY2Q2M2NlYjcwMjhhNDQ2ZDI2YmY1NjQ4NDQxYzEyYTRiY2YwY2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3ycdOBoOuTapJ2Y1O0DuLNDDYelF4dVWYFsgiqPd0DA)

2024-03-26 09:16 UTC, sunilsabatp approved these changes

2024-03-27 09:12 UTC, gangakhushlani approved these changes

2024-03-27 10:17 UTC, gangakhushlani commented
Planet labs will be in one line 
![Uploading Screenshot 2024-03-27 at 3.45.19 PM.png…]()

2024-03-27 10:51 UTC, gangakhushlani commented
<img width="181" alt="Screenshot 2024-03-27 at 3 45 19 PM" src="https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/160491167/06a720cc-f730-4119-9b5b-900c0b19512d">

2024-04-15 08:51 UTC, mohitb35 approved these changes

2024-04-15 08:52 UTC, mohitb35 approved these changes
LGTM

2024-04-17 06:06 UTC, merged