replaced core map library
Plant-for-the-Planet-org/planet-webapp pull request #2015
Opened 2024-03-21 13:31 UTC by mohitb35

replaced core map package(mapbox-gl -> maplibre-gl). 

Duplicate of #1999 which was deleted.

2024-03-26 06:18 UTC, prachigarg19 requested changes

2024-03-26 06:18 UTC, prachigarg19 commented on src/features/projects/components/maps/TimeTravel.tsx
> +      const compare = new MapboxCompare(before, after, container, {
`compare` variable is not being used anywhere. Could you just declare the object without initializing the value to a variable.

2024-03-26 06:18 UTC, prachigarg19 commented on src/features/projects/components/maps/TimeTravel.tsx
In this file `//@ts-ignore` has been used. This practice is not recommended. Is there a reason why this has been done? There aren't many errors in this file if we remove this.

2024-03-26 06:27 UTC, prachigarg19 approved these changes

2024-09-15 15:27 UTC, norbertschuler commented
Will the replacement of mapbox-gl with maplibre-gl be continued somewhere? Would be nice as it could reduce the overhead of code libraries to download a little bit for the website.

2024-09-16 06:29 UTC, mohitb35 commented
We are replacing mapbox-gl with maplibre-gl gradually. The new profile already uses this, and the upcoming facelift for the home page / project details page also uses maplibre.

2024-10-21 11:33 UTC, mohitb35 commented
Closing as not needed

2024-10-21 11:33 UTC, closed without merging