Feature/contribution apis
Plant-for-the-Planet-org/planet-webapp pull request #2064
Opened 2024-05-10 10:54 UTC by mohitb35

Fixes #

Check this list and then dismiss it:
- **Localization**
  - Have you added translation resources?
  - Have you localized numbers, dates and other stuff?
- **Validation and error management**
  - Is the user input validated?
  - Is the API response valided and are error responses properly handled?
  - Are errors caught if necessary?
- **Coding style**
  - Have you used a specific type for declaring the properties and parameters instead of `any`?
  - Have you defined interfaces for new components?
  - Have you added a source file not using TypeScript?
  - Have you checked if your newly introduced modules or functions are not already existing?
  - Is your `React.useEffect` using the right dependencies?
  - Check your code if it matches the existing code formatting.

Changes in this pull request:
-
-
-

@

2024-05-10 10:58 UTC, mohitb35 commented
@coderabbitai review

2024-05-16 08:38 UTC, sunilsabatp requested changes

2024-05-16 08:43 UTC, mohitb35 commented on src/features/common/types/myForestv2.d.ts
> +};
done

2024-05-16 08:56 UTC, sunilsabatp approved these changes

2024-05-16 08:58 UTC, merged