Asks user to acknowledge consent for recipient data (bulk codes)
Plant-for-the-Planet-org/planet-webapp pull request #2096
Opened 2024-06-19 10:56 UTC by mohitb35

Changes:
1. Adds a toggle requesting the user to acknowledge that they have taken consent for the provided recipient data while creating custom tree certificates
2. Moves charge consent text to the bottom of the form

2024-06-19 11:14 UTC, mariahosfeld reviewed
Functionality looks good to me.

2024-06-21 06:02 UTC, mohitb35 commented on src/features/user/BulkCodes/forms/IssueCodesForm.tsx
> +          </div>
Addressed in d840dc4

2024-06-21 06:02 UTC, mohitb35 commented on src/features/user/BulkCodes/forms/IssueCodesForm.tsx
> +    (bulkMethod === 'import' && !hasTakenRecipientDataConsent);
Addressed in d840dc4

2024-06-21 06:03 UTC, mohitb35 commented on src/features/user/BulkCodes/forms/IssueCodesForm.tsx
> +          </div>
ignore this

2024-06-21 06:05 UTC, mohitb35 commented on src/features/user/BulkCodes/forms/IssueCodesForm.tsx
> +    needsConsent;
That suggestion just inverts the logic to use AND conditions instead of OR. It does not make readability better according to me.

2024-06-21 06:21 UTC, mariahosfeld commented
Changes look good to me.

2024-06-21 06:26 UTC, mohitb35 commented on src/features/user/BulkCodes/forms/IssueCodesForm.tsx
> +            )}
Done in 4e9bfdf

2024-06-21 06:26 UTC, mohitb35 commented on src/features/user/BulkCodes/forms/IssueCodesForm.tsx
> +    needsConsent;
Done in https://github.com/Plant-for-the-Planet-org/planet-webapp/commit/4e9bfdfa0e49a2bc3302f6779dc3d27ec0ea9eb9

2024-06-21 07:26 UTC, sunilsabatp requested changes

2024-06-21 07:26 UTC, sunilsabatp commented on src/features/user/BulkCodes/forms/IssueCodesForm.tsx
> +                  style={{ cursor: 'pointer' }}
avoid using inline styling.

2024-06-21 09:18 UTC, sunilsabatp approved these changes

2024-06-21 10:43 UTC, merged