Feedback for My Forest V2
Plant-for-the-Planet-org/planet-webapp pull request #2125
Opened 2024-07-04 13:21 UTC by mohitb35

Addresses the following feedback for My Forest V2

1. Removes forced capitalization for profile name
2. Updates map credit tooltip styles, and repositions zoom controls/map credits in one column.
3. Removes border radius around profile background image, and uses a sharper background image
4. Standardizes border radius for all containers 
5. Hides the target on/off toggle switch if no target is entered
6. Resolves bug with clicking on Upload new profile image button
7. Displays a higher quality profile image version
8. Refactor to remove duplicate CustomTooltip components
9. Adds `showLeaderboard`/`exposeCommunity` functionality in the app
10. Wraps webapp button text properly
11. Minor tweaks to grid layout for responsiveness

2024-07-08 07:56 UTC, mariahosfeld reviewed
Changes look good to me so far.
Only issue: cannot check leaderboard functionality, due to already noted issue that needs to be resolved.

2024-07-09 03:56 UTC, sunilsabatp commented
While accessing a public profile, I encountered this error in the console

![image](https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/101264823/5a9ec8ab-8f7d-46c3-ad36-154c26001e40)

2024-07-09 04:45 UTC, sunilsabatp requested changes

2024-07-09 04:58 UTC, mohitb35 commented on src/features/user/MFV2/CommunityContributions/index.tsx
> +          <CustomTooltip height={15} width={14} color={'#828282'}>
Done

2024-07-09 04:58 UTC, mohitb35 commented on src/features/user/MFV2/ForestProgress/TargetFormInput.tsx
> +        {localTarget > 0 && (
Done

2024-07-09 05:09 UTC, mohitb35 commented
> While accessing a public profile, I encountered this error in the console
> 
> ![image](https://private-user-images.githubusercontent.com/101264823/346804109-5a9ec8ab-8f7d-46c3-ad36-154c26001e40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDIwMjksIm5iZiI6MTcyMDUwMTcyOSwicGF0aCI6Ii8xMDEyNjQ4MjMvMzQ2ODA0MTA5LTVhOWVjOGFiLThmN2QtNDZjMy1hZDM2LTE1NGMyNjAwMWU0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwNTA4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODkwMjY4NjA5MGIxYTkzNDU4YmRmZWFiMTA0MTJiYWVmMDhkZGQxYWM0ODAyMmQ0MDk5ODg3MjQ0NjZjMTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KJInqLWUnSBfNr9uDl3aF-Dex_5kGshMzO9lmF8_r30)

I'm guessing this was on localhost? Did you try `npx prisma generate` ?

2024-07-09 05:31 UTC, sunilsabatp commented
> > While accessing a public profile, I encountered this error in the console
> > ![image](https://private-user-images.githubusercontent.com/101264823/346804109-5a9ec8ab-8f7d-46c3-ad36-154c26001e40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDIwMjksIm5iZiI6MTcyMDUwMTcyOSwicGF0aCI6Ii8xMDEyNjQ4MjMvMzQ2ODA0MTA5LTVhOWVjOGFiLThmN2QtNDZjMy1hZDM2LTE1NGMyNjAwMWU0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwNTA4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODkwMjY4NjA5MGIxYTkzNDU4YmRmZWFiMTA0MTJiYWVmMDhkZGQxYWM0ODAyMmQ0MDk5ODg3MjQ0NjZjMTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KJInqLWUnSBfNr9uDl3aF-Dex_5kGshMzO9lmF8_r30)
> 
> I'm guessing this was on localhost? Did you try `npx prisma generate` ?

it's working now

2024-07-09 07:00 UTC, sunilsabatp approved these changes

2024-07-09 07:21 UTC, merged