Update webapp to adapt for new plant locations API
Plant-for-the-Planet-org/planet-webapp pull request #2208
Opened 2024-08-30 05:12 UTC by mohitb35

Changes:

- [ ] Update PlantLocation type (and related types)

Fixes #

Check this list and then dismiss it:
- **Localization**
  - Have you added translation resources?
  - Have you localized numbers, dates and other stuff?
- **Validation and error management**
  - Is the user input validated?
  - Is the API response valided and are error responses properly handled?
  - Are errors caught if necessary?
- **Coding style**
  - Have you used a specific type for declaring the properties and parameters instead of `any`?
  - Have you defined interfaces for new components?
  - Have you added a source file not using TypeScript?
  - Have you checked if your newly introduced modules or functions are not already existing?
  - Is your `React.useEffect` using the right dependencies?
  - Check your code if it matches the existing code formatting.

Changes in this pull request:
-
-
-

@

2024-09-02 07:23 UTC, mohitb35 commented on src/features/user/TreeMapper/components/Map.tsx
> +  setSelectedLocation: Function;
ignore this, as this expands the scope of the PR.

2024-09-02 07:23 UTC, mohitb35 commented on src/features/user/TreeMapper/components/PlantLocation.tsx
> +  setSelectedLocation: Function;
ignore this, as this expands the scope of the PR.

2024-09-03 06:53 UTC, sunilsabatp commented
`src/features/user/TreeMapper/Analytics/components/Map`
 resolve the type error for the above file

2024-09-03 08:52 UTC, sunilsabatp requested changes

2024-09-03 09:17 UTC, mohitb35 commented on src/features/user/TreeMapper/components/Map.tsx
> +          if (pl.type === 'multi-tree-registration') ids.push(`${pl.id}-layer`);
The condition is simple, and does not need extracting elsewhere, IMO.

2024-09-03 09:19 UTC, mohitb35 commented on src/features/user/TreeMapper/components/PlantLocation.tsx
> +              'multi-tree-registration' && treeCount
The condition is simple and does not need to be extracted elsewhere right now.

2024-09-03 09:20 UTC, mohitb35 commented on src/features/user/TreeMapper/components/PlantLocationPage.tsx
> +        {location.type === 'multi-tree-registration' &&
The condition is simple, does not to be extracted elsewhere

2024-09-03 09:21 UTC, mohitb35 commented on src/features/user/TreeMapper/components/TreeMapperList.tsx
>                  return (
Removed the unused import.

Not resolving the type error for now, as that can be addressed when we refactor the Treemapper functionality. Currently, only the minimum changes to make it work are being done.

2024-09-03 09:23 UTC, mohitb35 commented on src/features/user/TreeMapper/index.tsx
>                        }
Not resolving the type error for now, as that can be addressed when we refactor the Treemapper functionality. I suspect the entire code that looks for sample trees in the list of locations will need to be removed.

Currently, only the minimum changes to make it work are being done.

2024-09-03 09:59 UTC, mariahosfeld reviewed
Functionality looks good to me.

2024-09-03 10:07 UTC, mohitb35 reviewed
went through the comments and fixed/responded.

2024-09-03 10:16 UTC, sunilsabatp approved these changes
LGTM

2024-09-03 12:08 UTC, merged