Adds Plant Location Swiper functionality on Mobile
Plant-for-the-Planet-org/planet-webapp pull request #2259
Opened 2024-10-11 09:52 UTC by mohitb35

- [x] General swiper layout
- [x] Plant location details swiper
- [ ] Sample plant location swiper

2024-10-14 10:37 UTC, mariahosfeld commented
- [ ] With Safari/iOS the font color of the link to show the whole plot again is blue instead of black.
![Bildschirmfoto 2024-10-14 um 12 33 28](https://github.com/user-attachments/assets/236b30da-7dc9-4e49-b653-cdedcdb1d456)
- [ ] When using the "Show whole Plot" link, the height of the swiper is not correct. Refresh solves this, swiping to the next slide as well
![Bildschirmfoto 2024-10-14 um 12 34 51](https://github.com/user-attachments/assets/640fbb77-4dbd-496a-9459-fdb1e5b248e9)

2024-10-15 05:48 UTC, sunilsabatp commented
Should we consider moving the satellite layer icon elsewhere because it is completely hidden in some cases, or should we disable this feature when a plant location is selected?

<img width="242" alt="image" src="https://github.com/user-attachments/assets/877d3c79-51d6-415b-8f28-f36ea850fb1e">

2024-10-15 05:56 UTC, sunilsabatp commented
The expanded image mode for the plant location image slider is missing.
<img width="218" alt="image" src="https://github.com/user-attachments/assets/732d7833-7a80-4ffc-a962-9fc8eb445161">

2024-10-15 06:48 UTC, mariahosfeld commented
> The expanded image mode for the plant location image slider is missing. <img alt="image" width="218" src="https://private-user-images.githubusercontent.com/101264823/376475721-732d7833-7a80-4ffc-a962-9fc8eb445161.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzQ3NDIsIm5iZiI6MTcyODk3NDQ0MiwicGF0aCI6Ii8xMDEyNjQ4MjMvMzc2NDc1NzIxLTczMmQ3ODMzLTdhODAtNGZmYy1hOTYyLTlmYzhlYjQ0NTE2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwNjQwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjE4M2ZmM2QxNmM4NjU5ZDMzY2Y2Nzg1OTE4NGUzMjViMWVkMGQwZWY1NzM2ZmQ5OTViNTY4ZGRhZmEyM2NiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AFG5uiI_zNzEklcFqybz9kASXGe1IPnXkaPdMDydjuk">

We did this by design, as it will not expand much more on mobile.

2024-10-15 06:49 UTC, mariahosfeld reviewed
The height issue with the slider seems to be resolved.
But now I am also facing the issue, that at least for the first sample tree I have to tap 2x to see the details.
The issue was also there in older deployments, but due to the now resolved height issue I did not notice when testing them.

2024-10-15 07:31 UTC, mohitb35 commented
> The height issue with the slider seems to be resolved. But now I am also facing the issue, that at least for the first sample tree I have to tap 2x to see the details. The issue was also there in older deployments, but due to the now resolved height issue I did not notice when testing them.

Need to debug that, seems to be related to event handling on mobile devices.

2024-10-15 07:58 UTC, mariahosfeld commented
> > Should we consider moving the satellite layer icon elsewhere because it is completely hidden in some cases, or should we disable this feature when a plant location is selected?
> > <img alt="image" width="242" src="https://private-user-images.githubusercontent.com/101264823/376473996-877d3c79-51d6-415b-8f28-f36ea850fb1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Nzc2NDgsIm5iZiI6MTcyODk3NzM0OCwicGF0aCI6Ii8xMDEyNjQ4MjMvMzc2NDczOTk2LTg3N2QzYzc5LTUxZDYtNDE1Yi04ZjI4LWYzNmVhODUwZmIxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwNzI5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2QxN2JlZWIyMjg4MDY1YTVjNzJjY2JhMzIzM2Q0NmEzNDI3NTFiMGU4Yzc2MzkyOGIxNzI0MTRlNGRmMzBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ys0CMul7bMFzdMsIWxXHoZgSGfRCQzxgpUUdzTBo378">
> 
> I think we can hide the button in this scenario (on mobile devices).
> 
> @mariahosfeld thoughts?

I think so as well. On mobile we are either viewing the satellite layer or the plant locations.

2024-10-15 08:17 UTC, sunilsabatp requested changes

2024-10-15 11:40 UTC, mohitb35 commented on src/features/projectsV2/MobileInfoSwiper/index.tsx
> +  return (
I intentionally left it generic, so it could be used for any other purpose that we need.

2024-10-17 07:16 UTC, mohitb35 commented
> The height issue with the slider seems to be resolved. But now I am also facing the issue, that at least for the first sample tree I have to tap 2x to see the details. The issue was also there in older deployments, but due to the now resolved height issue I did not notice when testing them.

The 2x tap issue is now resolved.

2024-10-17 08:04 UTC, sunilsabatp approved these changes

2024-10-17 08:49 UTC, merged