feat: handle route for a project which has no site
Plant-for-the-Planet-org/planet-webapp pull request #2261
Opened 2024-10-15 12:20 UTC by sunilsabatp

- [ ] Handle case of setting site id to null when project has no sites. example (mothersforest project unselecting a plant location; ploc param remains in the url)

2024-10-15 13:06 UTC, mariahosfeld reviewed
Functionality looks good to me.

2024-10-18 07:08 UTC, mohitb35 commented on src/features/projectsV2/ProjectsMap/index.tsx
>        const result = getPlantLocationInfo(plantLocations, mapRef, e.point);
You could probably shorten this condition to 

`singleProject?.sites?.length === 0`

2024-10-18 07:09 UTC, mohitb35 commented on src/features/projectsV2/ProjectsContext.tsx
> +        updateUrlWithSiteId(locale, singleProject.slug, null);
This logic is a little confusing to me.

Why are we calling `updateUrlWithSiteId` directly? Why not pass in `null` to `updateSiteAndUrl`?

2024-10-18 07:10 UTC, mohitb35 requested changes
@sunilsabatp Please go through my comments

2024-10-21 10:27 UTC, mohitb35 approved these changes
LGTM

2024-10-21 10:28 UTC, merged