Projects redesign/project review clickable area
Plant-for-the-Planet-org/planet-webapp pull request #2268
Opened 2024-10-17 08:51 UTC by sunilsabatp

- [ ]  Include "Report" in the clickable area to download the project review (currently only the download symbol)
- [ ] Remove horizontal dividers in yellow box within project details

2024-10-17 09:53 UTC, mariahosfeld reviewed
Functionality looks good to me.

2024-10-18 05:22 UTC, mohitb35 commented on src/features/projectsV2/ProjectDetails/styles/ProjectInfo.module.scss
>    gap: 16px;
Minor refactor: 
1. The gap is common for keyInfoContainer and additionalInfoContainer, so perhaps that style can be kept in a common place

2024-10-18 05:32 UTC, mohitb35 commented on src/features/projectsV2/ProjectDetails/styles/ProjectReviews.module.scss
> +    margin-right: 6px;
Use a `gap` on the parent `a` tag instead of adding a `margin-right` - that approach is more consistent.

2024-10-18 05:37 UTC, mohitb35 requested changes
@sunilsabatp Have left some minor feedback

2024-10-21 10:06 UTC, mohitb35 approved these changes
LGTM

2024-10-21 10:07 UTC, merged