fix: handle site geometry null case
Plant-for-the-Planet-org/planet-webapp pull request #2275
Opened 2024-10-25 06:05 UTC by sunilsabatp

This PR addresses the case where a `project site geometry is null`, ensuring that the application handles this scenario gracefully without causing errors or unexpected behavior.

2024-10-25 06:14 UTC, mariahosfeld requested changes
For projects without sites I don't encounter any issues.
But when checking out a project with sites and treemapper data (/yucatan), I first see the vegetation layer and it takes a while (compared to the base) until the intended map with treemapper data shows up. Don't know if this is related, so please check and if needed amend.

2024-10-25 07:06 UTC, mohitb35 approved these changes
LGTM

2024-10-25 07:12 UTC, mohitb35 commented
> For projects without sites I don't encounter any issues. But when checking out a project with sites and treemapper data (/yucatan), I first see the vegetation layer and it takes a while (compared to the base) until the intended map with treemapper data shows up. Don't know if this is related, so please check and if needed amend.

I see this issue too.

2024-10-25 10:44 UTC, sunilsabatp commented
> > For projects without sites I don't encounter any issues. But when checking out a project with sites and treemapper data (/yucatan), I first see the vegetation layer and it takes a while (compared to the base) until the intended map with treemapper data shows up. Don't know if this is related, so please check and if needed amend.
> 
> I see this issue too. May not show up on local, unless you disable `reactStrictMode`

I have resolve this issue in this PR [projects-redesign/facelift-feedback](https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/2274)

2024-10-28 07:07 UTC, mariahosfeld reviewed
Now the sat layer is not shown when selecting /yucatan, but still a quite long latency for TreeMapper data to show. Maybe it is because of a first load of the project, but we need to keep an eye out and think about how we could optimize it.

2024-10-29 07:15 UTC, mohitb35 commented on src/features/projectsV2/ProjectsContext.tsx
> +    if (!singleProject?.sites) return;
I'm not sure why this was changed, but the sites array could be empty. In that case, we should not be able to set a selectedSite or add the site query param in the url

2024-10-29 07:46 UTC, mohitb35 approved these changes
@sunilsabatp Minor feedback, can address that and merge

2024-10-29 10:10 UTC, mohitb35 approved these changes
LGTM

2024-10-29 10:16 UTC, mohitb35 commented
@sunilsabatp 
1. While visiting `/prd/trees-for-peace-an-ayudh-europe-campaign`, the site with the null geometry remains in the url.
2. While visiting `/prd/mothersforest?site=asdfkjasfjsdnfjksdn`, the site param remains in the url even though the site is not found.

2024-10-30 07:19 UTC, mariahosfeld reviewed
Functionality looks good to me.

2024-10-30 12:46 UTC, mohitb35 approved these changes
LGTM

2024-10-30 12:46 UTC, merged