Projects redesign/font size
Plant-for-the-Planet-org/planet-webapp pull request #2283
Opened 2024-11-05 06:27 UTC by sunilsabatp

Points covered in this PR :

- Changed the position of the "Explore" button and updated its font size
- Updated the font size in the Project Info section

2024-11-05 07:13 UTC, mariahosfeld submitted a review, later dismissed
Please increase the font size of the highlighted (green) element from 8px to 10px
![image](https://github.com/user-attachments/assets/77ba6b92-7551-4b07-921b-bd822f171420)

2024-11-06 06:17 UTC, mohitb35 commented on src/features/projectsV2/ProjectDetails/styles/AboutProject.module.scss
> +    font-size: inherit;
Should we leave the "Read More" button font size as 10px?

2024-11-06 06:22 UTC, mohitb35 commented on src/features/projectsV2/ProjectDetails/styles/ProjectInfo.module.scss
> +  }
Please add a class selector for the styles applied for the year, it keeps things clearer.

2024-11-06 06:35 UTC, mohitb35 requested changes
@sunilsabatp please review my feedback

2024-11-06 08:56 UTC, mohitb35 approved these changes
LGTM

2024-11-06 09:03 UTC, merged