Address mgmt/edit address form
Plant-for-the-Planet-org/planet-webapp pull request #2307
Opened 2024-11-13 07:28 UTC by sunilsabatp

This PR handles edit address functionality.

2024-11-13 07:50 UTC, mariahosfeld reviewed
Functionality looks good.

2024-11-28 08:55 UTC, mohitb35 reviewed
@sunilsabatp please go through the feedback

2024-11-28 09:05 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/AddressManagment/microComponents/AddressFormInputs.tsx
1. Rename to `AddressForm`
2. Move common logic and buttons from `AddAddressForm` and `EditAddressForm` into this component. This includes validation, change handling, rhf setup etc.

2024-11-28 09:05 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/AddressManagment/AddAddressForm.tsx
Rename to AddAddress

2024-11-28 09:05 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/AddressManagment/EditAddressForm.tsx
Rename to EditAddress

2024-11-28 10:18 UTC, sunilsabatp commented on public/static/locales/en/profile.json
>    }
Could we handle the translation-related tasks at the end?

2024-11-29 05:19 UTC, sunilsabatp commented on public/static/locales/en/editProfile.json
It will be handled in a separate PR.

2024-11-29 05:20 UTC, sunilsabatp commented on src/features/user/Settings/EditProfile/AddressManagment/microComponents/AddressFormInputs.tsx
> +  errors: FieldErrors<FormData>;
The control prop has been removed.

2024-12-02 06:15 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/AddressManagment/microComponents/AddressFormWrapper.tsx
1. Match the file name and the component name. 
2. Update the component name where imported, if needed.
3. I'd suggest naming the `.addressFormContainer` class as `.addressFormLayout` since that matches the component name.

2024-12-02 06:19 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/AddressManagment/AddAddress.tsx
> +  const userCountry = user?.country || configCountry || 'DE';
Would `defaultCountry` or `initialCountry` be a better name here?

2024-12-02 06:23 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/AddressManagment/AddressManagement.module.scss
> +  }
As per the design, there should be more space between the last line of the form fields (state/country) and the buttons.

2024-12-02 06:34 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/AddressManagment/microComponents/AddressInput.tsx
@mariahosfeld As far as I can tell, the address suggest functionality is not too helpful. The results are erratic at best. A few examples:

1. I tried out my home address, but it could not find the building.
2. I tried out a random address in Mumbai, but after selecting it, the value in the city field was not what I expected, instead the locality was shown in the City field
3. I tried out the Plant-for-the-Planet address in Tutzing, but this wasn't found either.

Do we want to keep this?

2024-12-02 06:35 UTC, mohitb35 requested changes
@sunilsabatp

Have left some minor feedback. Once that's done, this is good to merge.

2024-12-02 09:00 UTC, mohitb35 approved these changes
LGTM

2024-12-02 09:00 UTC, mohitb35 approved these changes
LGTM

2024-12-02 09:04 UTC, merged