Address mgmt/address actions
Plant-for-the-Planet-org/planet-webapp pull request #2308
Opened 2024-11-14 10:30 UTC by sunilsabatp

This PR handle the address actions (`delete, setPrimary, setBilling`).

2024-11-27 07:57 UTC, mariahosfeld reviewed
Functionality looks good to me.

2024-12-02 10:07 UTC, mohitb35 commented on public/static/locales/en/profile.json
> +      "address2": "Address 2(optional)",
Do some of the keys that are currently outside need to be moved/grouped?

For example, I see `delete`, and `address2` keys

2024-12-04 05:21 UTC, mohitb35 requested changes
@sunilsabatp Mostly minor feedback, except for the state management of `addressAction`

2024-12-04 05:21 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/AddressManagment/AddressDeleteModal.tsx
> +    <div className={styles.addrConfirmContainer}>
I don't think `addrConfirmContainer` needs to be abbreviated.

2024-12-04 05:21 UTC, mohitb35 commented on src/features/user/Settings/EditProfile/AddressManagment/AddressManagement.module.scss
Could you clean up this scss file? Spacing between classes is erratic

2024-12-04 07:23 UTC, sunilsabatp commented on src/features/user/Settings/EditProfile/AddressManagment/AddressManagement.module.scss
I will handle this in this PR 
![image](https://github.com/user-attachments/assets/a017e311-8eaa-4ebe-9f3c-97a0103ffdbc)

2024-12-04 07:24 UTC, sunilsabatp commented on src/features/user/Settings/EditProfile/AddressManagment/AddressManagement.module.scss
I'll cover this in this  https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/2312

2024-12-04 09:45 UTC, mohitb35 approved these changes
@sunilsabatp Made a couple of small changes. LGTM.

2024-12-04 09:46 UTC, mohitb35 commented on public/static/locales/en/profile.json
> +      "addressConfirmationMessage": "Are you sure you want to set this address as your {addressType, select, mailing {billing} other {{addressType}}} address? {isAddressSet, select, true {This will r
Made this simpler in [035c34e](https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/2308/commits/035c34ed8d5326ecf0a48b0bfc79f5b0f5cb17e3)

2024-12-04 09:48 UTC, merged