Donor circle member badge
Plant-for-the-Planet-org/planet-webapp pull request #2317
Opened 2024-11-28 07:27 UTC by sunilsabatp

Handle rendering of donor circle member badge in profile card

- Display the donor circle member badge when `isMember` is `true` and the profile is set to private.
- Ensures the badge is conditionally rendered based on the `isPrivateAccount` and `isMember` status.
- Updated the profile card layout to accommodate the donor circle badge accordingly.

2024-11-28 07:46 UTC, mariahosfeld reviewed
Looks good to me.

2024-11-29 06:25 UTC, mohitb35 commented on package.json
> +    "@planet-sdk/common": "^0.1.43",
Update to 0.1.46 for the latest `user` type

2024-11-29 06:40 UTC, mohitb35 requested changes
@sunilsabatp Minor changes suggested

2024-11-29 06:40 UTC, mohitb35 commented on public/static/locales/en/profile.json
> +      "userDescription": "{bio}",
`userDescription` seems unnecessary and can be removed, even though this does not relate to the changes in the PR itself

2024-11-29 06:40 UTC, mohitb35 commented on src/features/user/Profile/ProfileCard/ProfileCard.module.scss
Avoid using absolute positioning unless absolutely necessary.

I tried out the styles below, and it seems to work as needed. 

```
.profileBackground {
  background-image: url('../../../../../public/assets/images/profile-bg-image.png');
  width: 100%;
  background-repeat: no-repeat;
  background-size: cover;
  min-height: 8rem;
  position: relative;
  @include mdTabletView {
    flex: 1;
  }
	// changed code below
  display: flex;
  justify-content: center;
  align-items: flex-end;
}

.donorCircleMemberBadge {
  width: max-content;
  display: flex;
  gap: 9px;
	// changed code below
  height: fit-content;
  margin-bottom: 4.5rem;
	// changed code above
  background: rgba(211, 234, 221, 1);
  border-radius: 16px;
  padding: 8px 16px;
  color: $primaryDarkColor;
  font-size: $fontXSmall;
  line-height: 16.34px;
  font-weight: 700;
  svg path {
    fill: $primaryDarkColor;
  }
}
```

2024-11-29 07:23 UTC, mohitb35 approved these changes
LGTM

2024-12-02 09:48 UTC, merged