fix: show correct unit type for manage projects list screen
Plant-for-the-Planet-org/planet-webapp pull request #2344
Opened 2024-12-27 06:09 UTC by sunilsabatp

#FIxes -
This PR ensures the correct unit type is used for restoration projects (unit type: m²; purpose: trees) in the "Manage Project" section.

2025-01-07 03:57 UTC, mohitb35 requested changes
@sunilsabatp Please go through my feedback

2025-01-07 03:57 UTC, mohitb35 commented on src/features/user/ManageProjects/ProjectsContainer.tsx
>            </p>
1. I suggest simply using something like
`tCommon(project.unitType, {formattedCount, count})` 
instead of handling different unitTypes in different ways. Make sure to not affect places that use the existing translation keys - you probably need new keys.

2. API needs to be updated to return `countPlanted` / `areaConserved` etc. for `unitType = 'm2'`. This should consider conservation projects as well. Discuss this with @jmiridis

3. Show the total units value if unitType is 'trees' or 'm2'.

4. Update the type of project to reflect the API response. Be specific about the values `unitType` can take.

2025-06-03 06:11 UTC, mohitb35 requested changes
- [x] Use the type from planet sdk once it is ready
- [x] After merging from develop, there is a client side error while impersonating the Plant-for-the-Planet tpo

```
TypeError: Cannot read properties of null (reading 'm2')

src/features/user/ManageProjects/ProjectsContainer.tsx (48:34)
  46 |     project.unitType === 'tree'
  47 |       ? (project as TreeProperties).unitsContributed?.tree
> 48 |       : project.unitsContributed.m2;
```

2025-07-02 10:49 UTC, mohitb35 approved these changes
LGTM

2025-07-02 11:05 UTC, mariahosfeld requested changes
Purpose Trees and unitType m2 is not correctly rendered.

2025-07-03 06:23 UTC, merged