user profile translations
Plant-for-the-Planet-org/planet-webapp pull request #389
Opened 2020-11-05 16:47 UTC by captainamiedi

Fixes #383 

Changes in this pull request:
- translate user details
-
-

@sagararyal

2020-11-06 19:03 UTC, sagararyal commented on public/static/locales/en/me.json
> +  "displayName": "{{name}}"
why is "userBio" and displayName this here?

2020-11-06 19:04 UTC, sagararyal commented on src/features/public/Donations/components/SingleProjectDetails.tsx
> +                text={t('donate:readMoreHalfText', {
why is this here as well? project description comes from API

2020-11-06 19:06 UTC, sagararyal commented on public/static/locales/en/forest.json
> +    "forestGift": "{{gift}}"
This looks useless as well

2020-11-06 19:06 UTC, sagararyal requested changes
Please remove unnecessary strings

2020-11-09 15:13 UTC, norbertschuler approved these changes
I have not checked if there are any text strings missed, but the patch looks ok for me.

2020-11-09 20:24 UTC, sagararyal commented
@norbertschuler 
The Project Name is not displayed on the List.
<img width="999" alt="Screen Shot 2020-11-09 at 9 24 04 PM" src="https://user-images.githubusercontent.com/5401575/98592375-ee82f080-22d1-11eb-8190-2f0db55881b3.png">

2020-11-10 08:59 UTC, norbertschuler requested changes

2020-11-10 08:59 UTC, norbertschuler commented on src/features/user/UserProfile/components/MyForestContainer.tsx
> +      <h6 className={styles.myForestTitleText}> {t('forest:myForest')} </h6>
A forest.json file does not exists yet!

2020-11-10 08:59 UTC, norbertschuler commented on src/features/user/UserProfile/components/UserInfo.tsx
> +  console.log(userprofile);
Remove console.log before merging this patch.

2020-11-10 09:09 UTC, norbertschuler approved these changes

2020-11-10 09:10 UTC, norbertschuler commented
> @norbertschuler
> The Project Name is not displayed on the List.

@sagararyal I fixed a lot of bugs introduced with this patch. Hopefully it is correct by now.

2020-11-10 10:06 UTC, merged