changed required div's to buttons
Plant-for-the-Planet-org/planet-webapp pull request #777
Opened 2021-01-25 08:40 UTC by rishsingh07

Fixes #

Check this list and then dismiss it:
- **Localization**
  - Have you added translation resources?
  - Have you localized numbers, dates and other stuff?
- **Validation and error management**
  - Is the user input validated?
  - Is the API response valided and are error responses properly handled?
  - Are errors caught if necessary?
- **Coding style**
  - Have you used a specific type for declaring the properties and parameters instead of `any`?
  - Have you defined interfaces for new components?
  - Have you added a source file not using TypeScript?
  - Have you checked if your newly introduced modules or functions are not already existing?
  - Is your `React.useEffect` using the right dependencies?
  - Check your code if it matches the existing code formatting.

Changes in this pull request:
-
-
-

@

2021-01-25 09:03 UTC, harshvitra commented on src/features/common/Layout/Navbar/Navbar.scss
> +button{
Move this to global scss

2021-01-25 09:07 UTC, harshvitra commented on src/features/user/ManageProjects/components/DetailedAnalysis.tsx
> +                    <button id={'backArrowDetailA'} className={`${styles.formFieldHalf}`}>
We don't need button here, the Animated button inside is already a button

2021-01-25 09:07 UTC, harshvitra commented on src/features/user/ManageProjects/components/ProjectMedia.tsx
> +          <button id={'backArrowProjectM'} className={`${styles.formFieldHalf}`}>
We don't need button here, the Animated button inside is already a button

2021-01-25 09:08 UTC, harshvitra commented on src/features/user/ManageProjects/components/ProjectSites.tsx
> +          <button id={'backArrowProjectS'} className={`${styles.formFieldHalf}`}>
We don't need button here, the Animated button inside is already a button

2021-01-25 09:10 UTC, harshvitra commented on src/features/user/UserProfile/components/RedeemModal.tsx
> +                <button id={'closeRedeemM'} onClick={() => closeRedeem()} className={styles.headerCloseIcon}>
Close this button tag

2021-01-25 09:10 UTC, harshvitra commented on src/features/user/UserProfile/components/EditProfileModal.tsx
>                      </div>
Close this button

2021-01-25 09:10 UTC, harshvitra commented on src/features/user/UserProfile/components/EditProfileModal.tsx
> +              <button id={'backButtonEditP'}
Close this button

2021-01-25 09:13 UTC, harshvitra commented on src/features/user/ManageProjects/components/ProjectSpending.tsx
> +                    <button  id={'backArrowProjectSpend'} className={`${styles.formFieldHalf}`}>
We don't need button here, the Animated button inside is already a button

2021-01-25 09:13 UTC, harshvitra requested changes
Fix the above comments

2021-01-26 10:05 UTC, harshvitra requested changes

2021-01-26 10:05 UTC, harshvitra commented on src/features/user/UserProfile/components/AddTargetModal.tsx
> +                <button className={spinnerStyle.spinner}></div>
This is not a button

2021-01-26 10:05 UTC, harshvitra commented on src/features/user/UserProfile/components/EditProfileModal.tsx
> +                    <button id={'userCamera'} className={styles.noProfilePic}>
This is not a button

2021-01-26 11:47 UTC, norbertschuler commented
Build fails with:

```
13:06:52.112 | Failed to compile.
-- | --
13:06:52.112 | ./src/features/user/UserProfile/components/AddTargetModal.tsx:114:57
13:06:52.112 | Syntax error: Expected corresponding JSX closing tag for <button>
13:06:52.112 | 112 \|             >
13:06:52.112 | 113 \|               {isLoadingForm ? (
13:06:52.112 | > 114 \|                 <button className={spinnerStyle.spinner}></div>
13:06:52.112 | \|                                                          ^
13:06:52.112 | 115 \|               ) : (
13:06:52.112 | 116 \|                 t('target:targetSave')
13:06:52.112 | 117 \|               )}


```

2021-01-26 11:48 UTC, norbertschuler commented on src/features/user/UserProfile/components/AddTargetModal.tsx
> +                <button className={spinnerStyle.spinner}></div>
- [ ] Build fails with:

```
13:06:52.112 | Failed to compile.
-- | --
13:06:52.112 | ./src/features/user/UserProfile/components/AddTargetModal.tsx:114:57
13:06:52.112 | Syntax error: Expected corresponding JSX closing tag for <button>
13:06:52.112 | 112 \|             >
13:06:52.112 | 113 \|               {isLoadingForm ? (
13:06:52.112 | > 114 \|                 <button className={spinnerStyle.spinner}></div>
13:06:52.112 | \|                                                          ^
13:06:52.112 | 115 \|               ) : (
13:06:52.112 | 116 \|                 t('target:targetSave')
13:06:52.112 | 117 \|               )}
```

2021-01-26 22:38 UTC, sagararyal commented
https://html.spec.whatwg.org/multipage/dom.html#element-attrdef-global-id

These IDs should be unique in the page. Which are not for example the button below:

![Screen Shot 2021-01-26 at 11 32 35 PM](https://user-images.githubusercontent.com/5401575/105914697-f596e080-602e-11eb-99eb-dc6d544a0408.png)


Something you can do is use the project guid to generate the id

for the single project
<div id="proj_eKBbIt7Bzavu9o7xzCAqjS2t" >

and for button 
<button id="don_proj_eKBbIt7Bzavu9o7xzCAqjS2t">


Menu buttons should be wrapped inside nav
<nav> 
<button> </button>
<button> </button>
<button> </button>
</nav>
![Screen Shot 2021-01-26 at 11 37 35 PM](https://user-images.githubusercontent.com/5401575/105915009-7bb32700-602f-11eb-9129-7c0c62681297.png)

2021-01-27 18:40 UTC, harshvitra commented
> Menu buttons should be wrapped inside nav

Let's create a different issue and branch for this. This branch is already too big.

2021-01-27 21:58 UTC, sagararyal commented
@rishsingh07 
![Screen Shot 2021-01-27 at 10 49 18 PM](https://user-images.githubusercontent.com/5401575/106059493-1163ba80-60f3-11eb-8cb1-f604f37af229.png)
these needs to be unique as well; and if possible make the keys shorter.

2021-01-30 17:11 UTC, merged