Fixed share button bug
Plant-for-the-Planet-org/planet-webapp pull request #854
Opened 2021-02-25 08:33 UTC by rishsingh07

Fixed #540 
@norbertschuler  Please check.

2021-02-25 09:44 UTC, norbertschuler commented
Still wrong testing this PR with https://planet-webapp-ltv8f0s1t-planetapp.vercel.app/t/norbert-schuler:

<img width="499" alt="Bildschirmfoto 2021-02-25 um 10 43 37" src="https://user-images.githubusercontent.com/1532418/109134485-5f9dc500-7756-11eb-854a-215601863fc4.png">

@sarveshpro can you test with Chrome?

2021-02-25 09:55 UTC, harshvitra commented
@rishsingh07 Can you implement the same changes for Personal profiles. 
(Log in and check from your own profile page)

2021-02-25 09:56 UTC, harshvitra commented
> Still wrong testing this PR with https://planet-webapp-ltv8f0s1t-planetapp.vercel.app/t/norbert-schuler:

There are 2 different menus: 1 for logged in users and 1 when I check someone's profile. 

Rishabh fixed one and the other has to be fixed

2021-02-25 11:48 UTC, norbertschuler approved these changes
LGFM

2021-02-26 08:53 UTC, harshvitra requested changes

2021-02-26 08:53 UTC, harshvitra commented on src/features/user/UserProfile/components/UserProfileOptions.tsx
> +            backgroundColor: "red",
Remove this

2021-02-26 09:03 UTC, harshvitra approved these changes

2021-02-26 09:03 UTC, merged