Signup enhancement
Plant-for-the-Planet-org/planet-webapp pull request #988
Opened 2021-04-15 10:25 UTC by rishsingh07

- [ ] Change the account selector to dropdown.
--> Individual changes to Person; and is default.

- [ ] Retrieve First & Last Name from Auth0 ID Token, and pre fill it when it is available.

- [ ] For Reforestation Organizations, prefill address from config api, when available.

2021-04-19 12:14 UTC, sagararyal commented
Please resolve the errors
- Crash on Reforestation Org due to loc.
- Layout issue on breakpoint < ~500px.

This was tested on Safari on macOS
https://user-images.githubusercontent.com/5401575/115234497-6115b900-a119-11eb-9f5d-d400ad65ff2f.mov

2021-04-19 13:55 UTC, norbertschuler requested changes

2021-04-19 13:55 UTC, norbertschuler commented on src/features/user/CompleteSignup/index.tsx
> +  const [type, setAccountType] = useState('person');
Why don't you just change the translation from `Individual` to `Person` and leave the rest unchanged? I think you can not change the value for the `type` state as it is also used to communicate the user type into the backend and your change probably will break the API call.

2021-04-27 05:10 UTC, sarveshpro commented
Error in complete signup
signup type - email signup
also remove token from console

Individual
![image](https://user-images.githubusercontent.com/27153515/116188227-af900c80-a744-11eb-9d33-b7d3fd9600ad.png)

TPO
![image](https://user-images.githubusercontent.com/27153515/116188365-ebc36d00-a744-11eb-8b82-b8d15e42f21a.png)

2021-04-28 09:13 UTC, norbertschuler requested changes

2021-04-28 09:13 UTC, norbertschuler commented on src/features/user/CompleteSignup/index.tsx
> +console.log(user,"h")
Please remove this before we merge the pull request.

2021-04-28 09:13 UTC, norbertschuler commented on src/features/user/CompleteSignup/index.tsx
> +console.log(token,"token")
Please remove this before we merge the pull request.

2021-04-28 09:13 UTC, norbertschuler commented on src/features/user/CompleteSignup/index.tsx
> +                            "" : getStoredConfig("loc").postalCode}
The registration currently fails for me saying no country is specified. Maybe this change for the country field is just a bug?

2021-04-28 09:16 UTC, norbertschuler commented
- [ ] On mobile devices the layout has some empty space between the bottom button and the bottom navigation when I test with a simulated iPhone X layout on Chrome on MacOS, but that's probably not related to this pull request:

<img width="367" alt="Bildschirmfoto 2021-04-28 um 11 05 45" src="https://user-images.githubusercontent.com/1532418/116379053-f2b8b100-a812-11eb-9a54-3dcaf44fd102.png">

2021-04-29 07:02 UTC, rishsingh07 commented
@norbertschuler can you please check the signing up process if you're able to do it.

2021-04-29 07:44 UTC, norbertschuler commented on src/features/user/CompleteSignup/index.tsx
> +                            "" : getStoredConfig("loc").postalCode}
I now get an error trying to signup (on staging):

<img width="1686" alt="Bildschirmfoto 2021-04-29 um 09 42 18" src="https://user-images.githubusercontent.com/1532418/116517554-6cae7000-a8cf-11eb-98fc-6b4967897eca.png">

2021-04-29 07:45 UTC, norbertschuler commented
> @norbertschuler can you please check the signing up process if you're able to do it.

I now get an error signing up (on staging):

<img width="1686" alt="Bildschirmfoto 2021-04-29 um 09 42 18" src="https://user-images.githubusercontent.com/1532418/116517711-99fb1e00-a8cf-11eb-8ea6-2ae65c7b6739.png">

2021-04-30 10:52 UTC, rishsingh07 commented
The issue was, the config was not present for staging. Sarvesh made it.

2021-04-30 12:48 UTC, norbertschuler approved these changes
Apart from the [layout bug](https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/988#issuecomment-828296192) which is probably not caused by this pull request, I think this patch works as intented.

2021-05-03 10:58 UTC, merged